### PR TITLE
Fix various metadata editor issues

### PR DESCRIPTION
**Pull request by gordlin**
### Related Item(s)
Issues:
#444 
#449 

### Changes
- [#444] Changes all subheadings in metadata form to `Sentence case`.
- [#449] Adds config language swap button to `Edit Metadata` modal.
- Prevents duplicate/incorrect toasts from showing up on metadata editor screen when no UUID entered/UUID doesn't exist.
- Makes minor styling modifications to editor Table of Contents.

### Testing
Steps:
#444:
1. Go to the `Create new product` screen, and scroll down to the metadata details form.
2. See that all headings are now in sentence case.

#449:
1. Open any product, and navigate through to the editor.
2. Click the `Edit Metadata` button in the sidebar.
3. You should see a `View English/French Config` button, allowing you to swap to the metadata for the other language.

Other:
1.  Back on the `Load Existing Storylines Product` page, ensure the UUID is blank and press "Load". You should only get ONE toast, telling you to enter a UUID first (before, you'd get multiple, with some saying that `UUID "" doesn't exist`).
2. Enter a non-existant UUID. You should get ONE toast notifying you the UUID doesn't exist.
3. Enter a UUID that exists. The form should pop up as expected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/484)

### CODE REVIEW

**Review by szczz — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Review by IshavSohal — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Review by yileifeng — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/484)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Pull request merged**
