### PR TITLE
Add video panel support in editor

### LINKED ISSUE #236: Support for video editor
See https://github.com/ramp4-pcar4/story-ramp/issues/359

Add some type of support in editor for video/audio panels. Must have flexibility for options including: Locally hosted video vs. Linked externally vs. YouTube video.

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
Closes #236 

### Changes
Integrated video panel editor in the slide editor. Supports two options: user-uploaded video or a URL that can be either a YouTube link or another external video source.

### Notes
Outstanding issues include: 
- attempting to save while on right panel does not save changes (#266)
- fixing user uploaded videos in preview mode (creating blob in preview tab does not work)
- adding support for uploading captions/transcripts for videos (#267)

### Testing
Test the new video panel editor for any bugs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/268)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by KashishMistry — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Updated with translations

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/268#-:-NuVJgl961c1JnD4WVEy:b-19pi26)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @KashishMistry, @RyanCoulsonCA, and @szczz)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/268)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
