### PR TITLE
Fix various formatting & accessibility issues

### PR DESCRIPTION
**Pull request by gordlin**
### Related Item(s)
Issues:
#451 
#434 
#435 
#463 

### Changes
- [#451] Change save warning toast text (`Please wait. Saving may take a few moments.`), and add i18n for save success toast.
- [#434, #435] Fix shadow/spacing issue on version history table.
- [#463] Set preview dropdown to show items on keyboard focus.

### Testing
Steps:

#434, #435:
1. Open a product with history (e.g. `00000000-0000-0000-0000-000000000000`).
2. Open the product history table by clicking `Show previous versions of product`. The table should be properly formatting, without extra shadow to the right.

#451:
1. For any product, add some changes and press save. See the new save warning text.
2. Change to French and repeat step 1. Notice that the save success message now has french text too.

#463:
1. On the editor, tab to the `Preview` dropdown button. 
2. Once you reach it, it should automatically show the dropdown upon focus, allowing you to tab to the language options.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)

### CODE REVIEW

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: all files reviewed, 1 unresolved discussion (waiting on @gordlin)

___
*[`src/lang/lang.csv` line 60 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479#-ODIdzx_8C5-SaVv7gBp:-ODIdzx_8C5-SaVv7gBq:blzobe7) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/746b75703a8d3469dd10f3ba12a67dd841fad829/src/lang/lang.csv#L60)):*
> ```CSV
> editor.editMetadata.message.successfulSave,Successfully saved changes!,1,Modifications enregistrées avec succès!,0
> editor.editMetadata.message.wait,Please wait. Saving may take a few moments.,1,"Veuillez patienter. L'enregistrement peut prendre quelques instants.",0
> editor.editMetadata.message.saveSuccess,Successfully saved changes!,1,Modifications enregistrées avec succès !,0
> ```

There's an extra space here in the French translation: `succès !`, other than that :lgtm:

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/lang/lang.csv` line 60 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479#-ODIdzx_8C5-SaVv7gBp:-ODNUfQj3zvYxalZ_Vds:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/746b75703a8d3469dd10f3ba12a67dd841fad829/src/lang/lang.csv#L60)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

There's an extra space here in the French translation: `succès !`, other than that :lgtm:
</blockquote></details>

Donethanks!

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Review by IshavSohal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: all files reviewed, 1 unresolved discussion (waiting on @gordlin)

___
*[`src/lang/lang.csv` line 60 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479#-ODNsVA89ykY03pKYlxO:-ODNsVA89ykY03pKYlxP:b-3ojlqj) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/e72b137500b2f14aca9a5c1d9547099562c50b43/src/lang/lang.csv#L60)):*
> ```CSV
> editor.editMetadata.message.successfulSave,Successfully saved changes!,1,Modifications enregistrées avec succès!,0
> editor.editMetadata.message.wait,Please wait. Saving may take a few moments.,1,"Veuillez patienter. L'enregistrement peut prendre quelques instants.",0
> editor.editMetadata.message.saveSuccess,Successfully saved changes!,1,Modifications enregistrées avec succès!,0
> ```

Seems like you duplicated the`editor.editMetadata.message.successfulSave` key. You can probably just stick with the old one.

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @IshavSohal and @RyanCoulsonCA)

___
*[`src/lang/lang.csv` line 60 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479#-ODNsVA89ykY03pKYlxO:-ODhUAj067u0D6cYkUz4:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/e72b137500b2f14aca9a5c1d9547099562c50b43/src/lang/lang.csv#L60)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Seems like you duplicated the`editor.editMetadata.message.successfulSave` key. You can probably just stick with the old one.
</blockquote></details>

Donethanks!

**Review by IshavSohal — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)

**Pull request merged**
