### PR TITLE
Button feedback improvements and other bug fixes

### LINKED ISSUE #52: Provide feedback when a button is selected
Clicking most buttons does not seem to do anything at the moment. However, buttons that do work, e.g. clicking "Save" does actually attempt to save the Storylines product to the server, but there is no feedback for the user to know that anything has happened.

### LINKED ISSUE #107: Logo external URL validation does not work as expected sometimes
For instance, if you type 'abcd' in the input field, the error message will not appear and it'll be like everything worked except a broken image is shown

### LINKED ISSUE #108: Panel type dropdown value changes even when cancelling
To reproduce this bug, try changing a panel's type but then click cancel. Notice how the panel will still be of the same type as before, but the value in the dropdown will have changed to the new type.

### PR DESCRIPTION
**Pull request by mohsin-r**
Closes #52.
Closes #107. 
Closes #108.

### Changes
* Clicking on various buttons such as load, save, etc. will now display feedback to the user in the form of a banner/popup at the top of the screen. 
* To address [this comment](https://github.com/ramp4-pcar4/storylines-editor/issues/52#issuecomment-1429910806), a custom confirmation modal will now be shown instead of  the browser's built-in one.
* Fixed a bug where typing nonsense text in the logo URL field did not display an error message (and instead displayed a broken image).
* Fixed a bug where the panel's type value would change in the dropdown even when you clicked cancel.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/109)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
Looks great!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/109#-:-NOz2MiH39D7Zc5PsLjc:b9bkkp1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Comment by mohsin-r** [comment]
Rebased.

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by roryhofland — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by yileifeng — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Pull request merged**
