### PR TITLE
Lazy Image Loading

### PR DESCRIPTION
**Pull request by roryhofland**
Closes [#315](https://github.com/ramp4-pcar4/story-ramp/issues/315)

Image panels are now lazily-loaded, meaning that they are only downloaded once a user has reached the part of the Storyline where the image sits.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/185)

### CODE REVIEW

**Comment by roryhofland** [comment]
*[`src/components/panels/slideshow-panel.vue` line 91 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/185#-NTnlRSh5I_lr6cCsk12:-NTnwZ5M2t1fvUSE0Qmp:be5s98e) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/dc2b57d534d3d5c4a1621ef98ba9b4bc090d4d95/src/components/panels/slideshow-panel.vue#L91)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

Getting the following console error on this line when attempting to preview:

> TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
 
I believe its because when you have one image that div doesn't render.
</blockquote></details>

Dunno how I missed that error. Added a check, donethanks.

**Review by mohsin-r — COMMENTED** [review]
Now multiple images don't seem to be visible on preview. The one image case is visible but the console grouses with a 404.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/185#-:-NTovxLl9GKa6RMY6xDf:b-670je0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by roryhofland — COMMENTED** [review]
> Now multiple images don't seem to be visible on preview

Wasn't able to replicate this so I'll wait for others to test for this bug

> this change will need to be made in https://github.com/ramp4-pcar4/story-ramp

Once this PR is merged I'll port the changes over to the story-ramp repo

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/185#-:-NTtpRAg9_pG_2OU2ah1:bnq3xz9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by yileifeng — COMMENTED** [review]
> Now multiple images don't seem to be visible on preview

I could reproduce this but seems to only apply to the first slide.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/185#-:-NTyCokE-Pgg0DqdA6qM:b-32zndx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Comment by roryhofland** [comment]
I can observe the bug now, it seems to only affect the build version as it works ok on local. Will investigate.

**Pull request closed without merging**
