### PR TITLE
fix race condition in Express server, add extra error checking

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Related Item(s)
No issue posted

### Changes
- Added some extra error checks to the Express server. It will return a 500 error code if there's an issue receiving the ZIP file through POST, ~~or if there's an issue decompressing the ZIP file.~~ (apparently the decompression library doesn't have an error handler)
- Fixed a race condition that resulted in the server returning OK to the editor before the file was finished decompressing.
- Increased max file size from 200MB to 300MB. This can be further increased if required.

### Notes
Please do your best to test this one thoroughly before we merge it in! 

### Testing
Steps:
1. Copy the code from this PR into the `server/index.js` file.
2. Play around with the editor as you usually would and make sure everything is being saved correctly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352)

### CODE REVIEW

**Review by dnlnashed — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by szczz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`server/index.js` line 50 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352#-O0nT1ep0d5nB5Mwd-xo:-O0nT1ep0d5nB5Mwd-xp:b-9yjztd) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/53b0da480310cd4bf65a076f23d776b02d71f8ad/server/index.js#L50)):*
> ```JavaScript
>     form.parse(req, function (err, field, file) {
>         if (err) {
>             logger('WARNING', 'Upload Aborted: an error has occurred while parsing the uploaded form: ', err);
> ```

Looks good! When you have a moment can you please push this to responseMessages as well?

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dnlnashed and @szczz)

___
*[`server/index.js` line 50 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352#-O0nT1ep0d5nB5Mwd-xo:-O0npjQs9ELbz3pNkXsJ:b-896fja) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/53b0da480310cd4bf65a076f23d776b02d71f8ad/server/index.js#L50)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Looks good! When you have a moment can you please push this to responseMessages as well?
</blockquote></details>

Done!

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/352)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
