### PR TITLE
update default map editor configs

### LINKED ISSUE #93: Map configuration - default to Lambert?
I'm not clear how much flexibility we have with regards to the FGPA authoring tool and modifications.
The "defaults" are underwhelming: Projections are in Mercator and the default basemaps are Esri-hosted. At a minimum, we would like to have a Lambert Conformal Conic (LCC) projection by default, and the NRCan-hosted basemaps featured in all of our applications. 
Working with these Mercator defaults, I cannot get any data to display. 
Are we able to modify the FGPA to include/replace these?

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #93 

Map editor now defaults to lambert, and config should be set to the English or French default based on the app language setting.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105)

### CODE REVIEW

**Review by roryhofland — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by spencerwahl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/editor/map-editor.vue` line 58 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105#-NOufHhH51vsGR_yHryJ:-NOufHhH51vsGR_yHryK:bp4dtbt) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/fcdae7e928b18b56b389ad9bfec49c5e1bd53535/src/components/editor/map-editor.vue#L58)):*
> ```Vue
> <script lang="ts">
> import { Component, Vue, Prop } from 'vue-property-decorator';
> import defaultConfigEn from '../../../public/scripts/ramp-editor/samples/map_en.json';
> ```

are `config-default.json` and `config-extent-3978.json` still used?

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[`src/components/editor/map-editor.vue` line 58 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105#-NOufHhH51vsGR_yHryJ:-NOugAn51QzW-1XFNNcV:b9j72cz) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/fcdae7e928b18b56b389ad9bfec49c5e1bd53535/src/components/editor/map-editor.vue#L58)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

are `config-default.json` and `config-extent-3978.json` still used?
</blockquote></details>

They are both used internally within the editor so I've left them in. `config-default.json` is used as a fallback if the config isn't provided for whatever reason, and `config-extent-3978.json` is used for setting the extent.

**Review by spencerwahl — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
