### PR TITLE
Add new lang selector landing page

### LINKED ISSUE #284: Language selector landing page
## Description

Allow the user to select a language when accessing the landing page for the Editor.

### Is your feature request related to a problem?

Users currently access the Editor via direct link, e.g. https://intranet.dev.ncr.ec.gc.ca/Storylines-Editor-STB/index.html#/en/editor. There is no ability to switch interface languages mid-session (we do not want this), and the user must manually change the URL to access the other language. 

## Proposed solution

If a user visits https://intranet.dev.ncr.ec.gc.ca/Storylines-Editor-STB/index.html or https://intranet.dev.ncr.ec.gc.ca/Storylines-Editor-STB/, present them with a landing page that allows them to choose between English and French. 

See https://canada.ca for an idea, does not need to fit the theme but layout-wise could be emulated:
image

## Alternatives considered

Open to ideas!

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
Closes #284 

### Changes
- [FEATURE] Added new language selector component as default landing page route
- [FIX] TS complaints 
- Adjusted file structure to remove the editor subfolder

### Testing
Links:
- https://ramp4-pcar4.github.io/storylines-editor/lang-landing-page
- https://ramp4-pcar4.github.io/storylines-editor/lang-landing-page/index-ca-en.html
- https://ramp4-pcar4.github.io/storylines-editor/lang-landing-page/index-ca-fr.html

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/304)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
