### PR TITLE
add return to landing button

### LINKED ISSUE #94: Back to Home link
A "Back to Home" link that takes you to the landing page (Create/Edit Storylines Product) would be useful. 

I am open to suggestions on where this could go. Right now, you must use the browser back button or change the URL manually.

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #94 

This PR adds a button that returns the user to the landing page. Hovering over the button will display a tooltip.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/120)

### CODE REVIEW

**Review by mohsin-r — APPROVED** [review]
Maybe this is a pointless grouse, but all the other buttons in the app have icon + text instead of icon + tooltip, so one thing to consider would be if we want to be consistent with that. It doesn't really bother me but bringing this up in case its worth discussing.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/120#-:-NQ5wTO9C54lSZpC-fmZ:br99f8p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Comment by RyanCoulsonCA** [comment]
Yeah we had a mini discussion [here](https://github.com/ramp4-pcar4/storylines-editor/issues/94) where we decided we didn't really want to over-clutter the header section with buttons. If we feel it's more practical to add the text then we can.

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by roryhofland — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
