### PR TITLE
Default UUID

### LINKED ISSUE #73: Auto-generate UUIDs
It would be nice if the user had a pre-generated UUID populating the UUID field for a new Storylines product. I've used this site in the past: https://www.uuidgenerator.net/, and Google even seems to generate one for you as well if you google "generate uuid". I would imagine there are countless libraries out there that can accomplish this.

### PR DESCRIPTION
**Pull request by roryhofland**
Closes #73 

The UUID field is now automatically populated when opening the metadata page for a new Storylines product.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/83)

### CODE REVIEW

**Comment by roryhofland** [comment]
https://ramp4-pcar4.github.io/storylines-editor/uuid/#/en/editor

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/83)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by mohsin-r — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/83#-:-NOGkxsa8lCp-YHDkUGu:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/83)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/83)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/83)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Pull request merged**
