### PR TITLE
Help button and panel

### PR DESCRIPTION
**Pull request by KashishMistry**
### Related Item(s)
#264 

### Changes
- Created a help button and panel, includes search bar and highlighting
- As the help documentation hasn't been uploaded to the repository yet (included @tosellob's help markdown file in this PR), the content displayed in the panel is the RAMP4 help documentation - that can be changed once the help documentation for RESPECT is uploaded

### Notes
helppanel

The images in the help content are not rendering on the page, if anyone has a fix for this, that would be appreciated, thanks!
icons

For future use of the `marked` npm library: the most recent version causes errors so try to use `marked v4.0.10` and install `@types/marked v4.0.1` as well.

### Testing
Steps:
1. Open the help panel by clicking on the help button (question mark icon) at the top right of the editor.
2. Try searching for a term in the search bar. Check if the term is getting highlighted (section titles will not be highlighted).
3. Expand and collapse sections.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/287)

### CODE REVIEW

**Comment by james-rae** [comment]
> The images in the help content are not rendering on the page, if anyone has a fix for this, that would be appreciated, thanks!

Longshot, but in ramp's `package.json`, there is this script entry

```
"postbuild": "(rm dist/bad.css || true) && cp -a public/. dist/"
```

Not sure what the `bad.css` is about but looks like this is also copying files from `public` to `dist`, which might be needed to move the images over to where things build?

This isnt in respect editors `package.json`. Might get lucky.

**Comment by KashishMistry** [comment]
Thanks, added the script entry if it helps with any issues in the future, but images are not rendering in this case.

**Comment by dan-bowerman** [comment]
Implement Yi Lei's vite PRs first, then do the needful to make this one work. This PR is probably too stale to merge as-is.

**Comment by yileifeng** [comment]
Closing this PR as work is still incomplete and demo link broken, whoever assigns the issue can work off this branch.

**Pull request closed without merging**
