### PR TITLE
Fix accessibility errors

### PR DESCRIPTION
**Pull request by IshavSohal**
### Related Item(s)
#362 

### Changes
- Fixed accessibly errors in
  - Main editor page
  - New product page
  - Edit existing product page
  - Choose language page
  - Create/Edit product option page

### Notes
- There are still a few accessibility issues remaining, which I believe are all issues with the highcharts editor

### Testing
Steps:
1. Open storylines to the 'choose language page'. Open the WAVE extension and observe that there are no (non-highcharts) errors
2. Click English to open the 'create/edit product option' page. Open the WAVE extension and observe that there are no (non-highcharts) errors
3. Click on the 'Create New Storylines Product' button to open the 'new product page'. Open the WAVE extension and observe that there are no (non-highcharts) errors
4. Go back to the 'create/edit product option page'
5. Click on the 'Edit Existing Storylines Product Button' to open the 'edit existing product' page. Enter an uuid of:
```
00000000-0000-0000-0000-000000000000
```
6. Open the WAVE extension and observe that there are no (non-highcharts) errors
7. Click the 'Load' button. Open the WAVE extension and observe that there are no (non-highcharts) errors
8. Click the 'Next' button to open the main editor page. Open the WAVE extension and observe that there are no (non-highcharts) errors

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
Few more errors generated using WAVE (many of these are the same error across different editor types):

Image editor
- low contrast on "browse" (in file upload area)
- empty button on delete icon
- missing form labels (alt tag input, image caption input, slideshow caption)

Dynamic editor
- empty table header for the add new panel row
- missing form label on the "Enter Panel ID" input

Advanced editor
- low contrast on switch editor mode button

RAMP editor (issue for RAMP config repo)
- missing form labels for all inputs
- many empty buttons for all information mini-icons

Chart editor
- low contrast on "Empty" text when there are no charts
- empty button on delete icon

Video editor
- low contrast on "browse" (same as image editor)
- missing form labels (video title, URL input)
- empty button on delete icon

Slideshow editor
- missing form label (slideshow caption)
- empty table header (on table header row)

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O4zcLAO0upcGdgpwiBo:b-2tthbm)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/editor.vue` line 22 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zjvqH5qM3_kULWLQN:-O4zjvqH5qM3_kULWLQO:b-444cv5) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/editor.vue#L22)):*
> ```Vue
>                             transform="translate(-0.5)"
>                         />
>                         .
> ```

I think instead of doing this adding an aria-label attribute to the <a> element would be a better fix
___
*[`src/components/slide-toc.vue` line 29 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zlCdPAM92y6vAy3cb:-O4zlCdPAM92y6vAy3cc:brbdfio) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/slide-toc.vue#L29)):*
> ```Vue
>                         d="M5 22q-.825 0-1.413-.587Q3 20.825 3 20V6h2v14h11v2Zm4-4q-.825 0-1.412-.587Q7 16.825 7 16V4q0-.825.588-1.413Q8.175 2 9 2h9q.825 0 1.413.587Q20 3.175 20 4v12q0 .825-.587 1.413Q18.825 18 18 18Zm0-2h9V4H9v12Zm0 0V4v12Z"
>                     />
>                     -
> ```

same as earlier, try aria-label

**Review by IshavSohal — COMMENTED** [review]
Thanks for the help. I was able to fix all of the errors you listed (apart from the RAMP config editor ones) except for the 'low contrast' error on the switch editor mode button within the advanced editor. I think it's because this button is a part of the `json-editor` component (within `custom-editor.vue`). 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O5KZQdvCGzU8L-jMITI:b-cbu5fb)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @yileifeng)

___
*[`src/components/editor.vue` line 22 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zjvqH5qM3_kULWLQN:-O5K_N4G3FX3cRHQlENN:b-qurh3g) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/editor.vue#L22)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

I think instead of doing this adding an aria-label attribute to the <a> element would be a better fix
</blockquote></details>

Good idea, donethanks
___
*[`src/components/slide-toc.vue` line 29 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zlCdPAM92y6vAy3cb:-O5K_fJD6vjuDeQMz3tn:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/slide-toc.vue#L29)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

same as earlier, try aria-label
</blockquote></details>

Donethanks

**Review by yileifeng — COMMENTED** [review]
Most of the editor specific WAVE errors got cleared so nice work, will make a new issue for the RAMP config accessibility errors. Just one more error popping up on the video editor: 
- missing form label on the paste URL input for video editor

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O5PGc9bDzOCnnx5I4fV:b-ja708t)* status: 0 of 15 files reviewed, 2 unresolved discussions

**Review by spencerwahl — CHANGES_REQUESTED** [review]
All of the labels and such should be put in the lang csv so french can be added as well

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O5PJvOVAWyHae-qugw4:b-iomt6x)* status: 0 of 15 files reviewed, 8 unresolved discussions (waiting on @IshavSohal and @yileifeng)

___
*[`src/components/dynamic-editor.vue` line 54 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PHR1h3HyVdleyPvFN:-O5PHR1iA6t6uWH2T0Ve:b-os1z8n) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/dynamic-editor.vue#L54)):*
> ```Vue
>                     <th class="flex flex-col items-center" aria-label="Enter Panel ID">
>                         <label for="panelId" aria-label="Enter Panel ID"></label>
>                         <input
> ```

If the label isn't being made visible, there should just be an `aria-label` directly on the `input` element. I also don't believe the table header needs an aria-label as it is not focusable.
___
*[`src/components/editor.vue` line 22 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zjvqH5qM3_kULWLQN:-O5PGkii9offtdObc9Gy:bbl37dt) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/editor.vue#L22)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Good idea, donethanks
</blockquote></details>

The aria-label should go on the focusable element here, which should be the `router-link`
___
*[`src/components/image-editor.vue` line 55 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PIEZn-LcOWaVQLCAA:-O5PIEZn-LcOWaVQLCAB:b-lmj5cs) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/image-editor.vue#L55)):*
> ```Vue
>                         <label class="editor-label text-label" for="altTag">{{ $t('editor.image.altTag') }}:</label>
>                         <input
>                             id="altTag"
> ```

Because the alt tag and image caption inputs appear for each image, these `id`s get duplicated, which will cause issues. I would append the index or the id above or some otherwise differentiating string to the end of the id.
___
*[`src/components/slide-toc.vue` line 29 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zlCdPAM92y6vAy3cb:-O5PImrdC05TC4-p3ht1:b-spojas) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/slide-toc.vue#L29)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Donethanks
</blockquote></details>

same as above, aria-label should move to the button
___
*[`src/components/slideshow-editor.vue` line 55 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJG6J2DK3EDyN_CCa:-O5PJG6K6uhjVBU9Wtd9:b-ngdi68) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/slideshow-editor.vue#L55)):*
> ```Vue
>             <thead>
>                 <tr class="table-header">
>                     <th aria-label="empty header"></th>
> ```

The labels should be useful info, I would label this "slide number" or "index" or something similar
___
*[`src/components/helpers/chart-preview.vue` line 16 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJO4m1oFbMTq7klfV:-O5PJO4m1oFbMTq7klfW:bgiv3h1) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/helpers/chart-preview.vue#L16)):*
> ```Vue
>                     viewBox="0 0 352 512"
>                     xmlns="http://www.w3.org/2000/svg"
>                     :aria-label="$t('editor.chart.delete')"
> ```

same as above for both of these svg labels
___
*[`src/components/helpers/image-preview.vue` line 15 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJSjtBqjZ2DvSAs6H:-O5PJSjtBqjZ2DvSAs6I:b-7tdrph) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/helpers/image-preview.vue#L15)):*
> ```Vue
>                     viewBox="0 0 352 512"
>                     xmlns="http://www.w3.org/2000/svg"
>                     :aria-label="$t('editor.image.delete')"
> ```

again
___
*[`src/components/helpers/video-preview.vue` line 10 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJVkK3U4W0TAewUd8:-O5PJVkK3U4W0TAewUd9:b-7tdrph) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/helpers/video-preview.vue#L10)):*
> ```Vue
>                 v-tippy="{ placement: 'top', hideOnClick: false, animateFill: true }"
>             >
>                 <svg height="24px" width="24px" viewBox="0 0 352 512" xmlns="http://www.w3.org/2000/svg" :aria-label="$t('editor.video.delete')">
> ```

again

**Review by IshavSohal — COMMENTED** [review]
Donethanks. I think I got all of them, but let me know if I've missed any

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O5tM4N0C3eZcGtCu6hV:bz9jeb4)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[`src/components/dynamic-editor.vue` line 54 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PHR1h3HyVdleyPvFN:-O5tLA7C5oPqLMIIYa1e:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/dynamic-editor.vue#L54)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

If the label isn't being made visible, there should just be an `aria-label` directly on the `input` element. I also don't believe the table header needs an aria-label as it is not focusable.
</blockquote></details>

Donethanks
___
*[`src/components/editor.vue` line 22 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zjvqH5qM3_kULWLQN:-O5tLMYf-oD4A78d2x_l:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/editor.vue#L22)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

The aria-label should go on the focusable element here, which should be the `router-link`
</blockquote></details>

Donethanks
___
*[`src/components/image-editor.vue` line 55 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PIEZn-LcOWaVQLCAA:-O5tLR_7C9eLPUtfdDH9:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/image-editor.vue#L55)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

Because the alt tag and image caption inputs appear for each image, these `id`s get duplicated, which will cause issues. I would append the index or the id above or some otherwise differentiating string to the end of the id.
</blockquote></details>

Donethanks
___
*[`src/components/slide-toc.vue` line 29 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O4zlCdPAM92y6vAy3cb:-O5tLntP1yQjyXf4yyaI:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f1144b798ce42c4ecf8793093a9cdeebb4299971/src/components/slide-toc.vue#L29)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

same as above, aria-label should move to the button
</blockquote></details>

Donethanks
___
*[`src/components/slideshow-editor.vue` line 55 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJG6J2DK3EDyN_CCa:-O5tLp1e8LCIReoy7YGC:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/slideshow-editor.vue#L55)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

The labels should be useful info, I would label this "slide number" or "index" or something similar
</blockquote></details>

Donethanks
___
*[`src/components/helpers/chart-preview.vue` line 16 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJO4m1oFbMTq7klfV:-O5tLuDQ5rjhm3HOc-dx:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/helpers/chart-preview.vue#L16)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

same as above for both of these svg labels
</blockquote></details>

Donethanks
___
*[`src/components/helpers/image-preview.vue` line 15 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJSjtBqjZ2DvSAs6H:-O5tLzY7EsOTYQDeecP_:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/helpers/image-preview.vue#L15)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

again
</blockquote></details>

Donethanks
___
*[`src/components/helpers/video-preview.vue` line 10 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O5PJVkK3U4W0TAewUd8:-O5tM1OS8e0PVljXQkZQ:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f0f0e312aa1bc30e393530ed5754263e2cc3c7ae/src/components/helpers/video-preview.vue#L10)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

again
</blockquote></details>

Donethanks

**Comment by IshavSohal** [comment]
> Most of the editor specific WAVE errors got cleared so nice work, will make a new issue for the RAMP config accessibility errors. Just one more error popping up on the video editor:
> 
> * missing form label on the paste URL input for video editor
> 
> > _[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O5PGc9bDzOCnnx5I4fV:b-ja708t)_ status: 0 of 15 files reviewed, 2 unresolved discussions

Sorry, forgot to respond to this earlier. I'm not getting this error on my end. Is it still occurring for you?

**Review by yileifeng — COMMENTED** [review]
Just re-tested and seems like it: 


 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O6NAvWM4z82YFBP-ZVu:bimrdtg)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @spencerwahl)

**Comment by IshavSohal** [comment]
Should be fixed now.

**Review by yileifeng — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 10 files at r2, 8 of 11 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 8 unresolved discussions (waiting on @spencerwahl)

**Review by yileifeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 8 unresolved discussions (waiting on @spencerwahl)

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
Looks good! I've just caught a few more small things.

> Reviewed 4 of 7 files at r1, 1 of 10 files at r2, 7 of 11 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-:-O6v4NICDyKyxEPCAKfU:b9wko76)* status: all files reviewed, 13 unresolved discussions (waiting on @IshavSohal, @spencerwahl, and @yileifeng)

___
*[`src/components/dynamic-editor.vue` line 53 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v03GF68unrfcJOa6J:-O6v03GF68unrfcJOa6K:b-qiqsak) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/dynamic-editor.vue#L53)):*
> ```Vue
>                 <tr class="table-add-row">
>                     <th class="flex flex-col items-center">
>                         <label for="panelId"></label>
> ```

This is empty so we don't actually need it at all. The `aria-label` on the input below is good enough!
___
*[`src/components/slide-editor.vue` line 244 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v1Rwy7Ov-Z8xkAQaw:-O6v1Rwy7Ov-Z8xkAQax:b-g9jer1) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/slide-editor.vue#L244)):*
> ```Vue
>                     <span class="ml-auto flex-grow"></span>
>                     <div v-if="!advancedEditorView || rightOnly" class="flex flex-col mr-8">
>                         <label class="editor-label text-left text-lg">{{ $t('editor.slides.contentType') }}:</label>
> ```

This guy needs a `for` attribute as well.
___
*[`src/components/text-editor.vue` line 5 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v3ZEl9pJVQQ_13137:-O6v3ZEl9pJVQQ_13138:brxhv9i) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/text-editor.vue#L5)):*
> ```Vue
>         <label class="editor-label text-left" for="panelTitle">{{ $t('editor.slides.panel.title') }}:</label>
>         <input class="editor-input" type="text" id="panelTitle" v-model="panel.title" />
>         <label class="editor-label text-left mt-2">{{ $t('editor.slides.panel.body') }}:</label>
> ```

Needs a `for attribute as well.
___
*[`src/components/helpers/metadata-content.vue` line 34 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v-PgV-4xMWj9ojaxd:-O6v-PgWDChjxNzk5D3Z:b-p41a4f) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/helpers/metadata-content.vue#L34)):*
> ```Vue
>         
>         <div v-if="!!metadata.logoPreview">
>             <label class="editor-label">{{ $t('editor.logoPreview') }}:</label>
> ```

This guy needs a `for` attribute like the others. It currently gives an `orphaned form label` warning in WAVE.
___
*[`src/components/helpers/metadata-content.vue` line 39 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v-MIi1SSCNMN1x8GJ:-O6v-MIi1SSCNMN1x8GK:bbair3e) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/helpers/metadata-content.vue#L39)):*
> ```Vue
>                 v-if="!!metadata.logoPreview && metadata.logoPreview != 'error'"
>                 class="image-preview"
>                 alt="preview of product logo"
> ```

This should have a translation

**Review by IshavSohal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: 11 of 16 files reviewed, 13 unresolved discussions (waiting on @RyanCoulsonCA, @spencerwahl, and @yileifeng)

___
*[`src/components/dynamic-editor.vue` line 53 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v03GF68unrfcJOa6J:-O6wXYMy9GahmBrIht5y:b-9ymypn) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/dynamic-editor.vue#L53)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This is empty so we don't actually need it at all. The `aria-label` on the input below is good enough!
</blockquote></details>

Donethanks. I also ended up adding the aria label back to the table header because I was getting an 'empty table header' error. 
___
*[`src/components/slide-editor.vue` line 244 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v1Rwy7Ov-Z8xkAQaw:-O6wXuhP-4GZtens8hx0:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/slide-editor.vue#L244)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This guy needs a `for` attribute as well.
</blockquote></details>

Donethanks
___
*[`src/components/text-editor.vue` line 5 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v3ZEl9pJVQQ_13137:-O6wXxLJBp7PmzeOmINB:bqzr676) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/text-editor.vue#L5)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Needs a `for attribute as well.
</blockquote></details>

Since this label didn't have a corresponding form control, I just made it a div instead. Is this fine?
___
*[`src/components/helpers/metadata-content.vue` line 34 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v-PgV-4xMWj9ojaxd:-O6wYBACC38vd2TC6aL9:b-aioo9g) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/helpers/metadata-content.vue#L34)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This guy needs a `for` attribute like the others. It currently gives an `orphaned form label` warning in WAVE.
</blockquote></details>

Also ended up making this a div. 
___
*[`src/components/helpers/metadata-content.vue` line 39 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v-MIi1SSCNMN1x8GJ:-O6wYABr7R3nDJVdkpp4:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/helpers/metadata-content.vue#L39)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This should have a translation
</blockquote></details>

Donethanks

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: 5 of 16 files reviewed, 10 unresolved discussions (waiting on @IshavSohal, @spencerwahl, and @yileifeng)

___
*[`src/components/dynamic-editor.vue` line 53 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v03GF68unrfcJOa6J:-O700q577tYJ_KYaT8QT:bqhcfh8) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/dynamic-editor.vue#L53)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Donethanks. I also ended up adding the aria label back to the table header because I was getting an 'empty table header' error.
</blockquote></details>

Whoops this is actually a mistake on my part when I implemented this feature. These cells should be `td`, not `th`. The only place we need `th` is in the first row. Just swap these with `td` (and change the `.table-add-row th` CSS selector at the bottom of the file to `.table-add-row td`), remove that aria-label and you shouldn't get an error anymore :)
___
*[`src/components/text-editor.vue` line 5 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v3ZEl9pJVQQ_13137:-O702ZMW1p7xN_hmbsUn:bw8d34i) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/text-editor.vue#L5)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Since this label didn't have a corresponding form control, I just made it a div instead. Is this fine?
</blockquote></details>

Yup, should be ok!
___
*[`src/components/helpers/metadata-content.vue` line 134 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O703I6tDL2hj6ezU7gV:-O703I6tDL2hj6ezU7gW:b-ekt4y1) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/bb00169658d121a20f609c7e691ea5893bd1a0bd/src/components/helpers/metadata-content.vue#L134)):*
> ```Vue
>             <option value="horizontal">{{ $t('editor.tocOrientation.horizontal') }}</option>
>         </select>
>         <label class="editor-label ml-25">{{ $t('editor.returnTop') }}</label>
> ```

This one isn't your fault either, but this PR just got merged in and we let another accessibility error slip through :facepalm:. Should just need a `for` like the ToC orientation checkbox.

**Review by IshavSohal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: 5 of 16 files reviewed, 10 unresolved discussions (waiting on @RyanCoulsonCA, @spencerwahl, and @yileifeng)

___
*[`src/components/dynamic-editor.vue` line 53 at r5](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O6v03GF68unrfcJOa6J:-O75sape40Nu2IxWzFyI:bat8ibk) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/09e2b3992e4ae71bc71b1d6e43aece5a8b9bc9ab/src/components/dynamic-editor.vue#L53)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Whoops this is actually a mistake on my part when I implemented this feature. These cells should be `td`, not `th`. The only place we need `th` is in the first row. Just swap these with `td` (and change the `.table-add-row th` CSS selector at the bottom of the file to `.table-add-row td`), remove that aria-label and you shouldn't get an error anymore :)
</blockquote></details>

All good, donethanks
___
*[`src/components/helpers/metadata-content.vue` line 134 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379#-O703I6tDL2hj6ezU7gV:-O75sjQ_ABMzSlT6kMOS:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/bb00169658d121a20f609c7e691ea5893bd1a0bd/src/components/helpers/metadata-content.vue#L134)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This one isn't your fault either, but this PR just got merged in and we let another accessibility error slip through :facepalm:. Should just need a `for` like the ToC orientation checkbox.
</blockquote></details>

Donethanks!

**Review by RyanCoulsonCA — COMMENTED** [review]
> Reviewed 1 of 5 files at r6, 8 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 9 unresolved discussions (waiting on @spencerwahl and @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 9 unresolved discussions (waiting on @spencerwahl and @yileifeng)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 5 files at r6, 9 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 9 unresolved discussions (waiting on @spencerwahl)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 3 of 11 files at r3, 1 of 1 files at r5, 1 of 5 files at r6, 9 of 10 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

**Review by yileifeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Pull request merged**
