### PR TITLE
Chart bug fixes

### LINKED ISSUE #96: Dropdowns in Chart editor are appearing far below where they should
While still mostly functional, the dropdowns in the chart editor are appearing well below where they should be. In some cases, the dropdown is cut-off by the bottom of the screen and it's difficult to see what options are available.
image

### PR DESCRIPTION
**Pull request by roryhofland**
Closes #96, #114.

The edit chart button no longer spawns multiple editor windows on repeat presses, and dropdown menus should now appear in the correct position within the editor.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/118)

### CODE REVIEW

**Review by mohsin-r — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Pull request merged**
