### PR TITLE
Migrate Storylines Editor to Vue3

### PR DESCRIPTION
**Pull request by dnlnashed**
Related Issues: #192 #216 #237 

Done together with @yileifeng 

### Changes ###
- Updated Vue to version 3 (including global API + syntax changes, dynamic components registration, TS)
- Various dependencies updated to work with Vue3
  - `vue2-modals` was replaced with `vue-final-modal`
- Added the new `ramp-storylines` Vue3 plugin from https://www.npmjs.com/package/ramp-storylines
   - Enables support for Storylines preview and individual panel previews without needing all the Storylines code
- Various bug fixes found before and after the refactor

### Future Tasks ###
- Refactor options to composition API

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/242)

### CODE REVIEW

**Comment by dnlnashed** [comment]
Demo link: https://ramp4-pcar4.github.io/storylines-editor/vue3-refactor/#/en/editor

**Review by spencerwahl — APPROVED** [review]
Things all look to be working correctly when I poke around the demo

> Reviewed 33 of 49 files at r1, 1 of 5 files at r2, 2 of 9 files at r3, 4 of 6 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/242#-:-Nntw34i6VvLSFJFF-Ae:bmeww7z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Review by RyanCoulsonCA — APPROVED** [review]
Briefly looked over all of the code and it looks good to me! I also tested loading existing products and creating a new one and that all seems good as well.

I did notice one small thing: when you preview a product, it's not displaying the logo at the top. I'll log a new issue for this though.


> Reviewed 33 of 49 files at r1, 1 of 5 files at r2, 2 of 9 files at r3, 4 of 6 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/242#-:-NntzeYtEuLkYNvh9udy:b-es9v82)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Review by james-rae — APPROVED** [review]
> Reviewed 33 of 49 files at r1, 1 of 5 files at r2, 2 of 9 files at r3, 4 of 6 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/242)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Review by milespetrov — APPROVED** [review]
lgtm - the build and tooling might benefit from future updates, there have been quite a few changes with v3 and even changes during the v3 lifecycle. For now though this is totally fine.

> Reviewed 1 of 49 files at r1, 1 of 9 files at r3, 1 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/242#-:-NnysApg-maT-u1sCeD9:bnw9zh0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Review by szczz — APPROVED** [review]
> Reviewed 33 of 49 files at r1, 1 of 5 files at r2, 2 of 9 files at r3, 4 of 6 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/242)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dnlnashed)

**Pull request merged**
