### PR TITLE
rebase help panel

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Related Item(s)
#264 

### Changes
- Rebased Kashish's help panel PR. The only change I've made was to how we're fetching the markdown files in order to fix the issue she was having with loading image.s

### Testing
Steps:
1. Open the demo page and load a product.
2. There should be a new `?` button in the top right. Clicking it should display some help content.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351)

### CODE REVIEW

**Review by yileifeng — APPROVED** [review]
Will need some rebasing if Vite PR is merged but looks good

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351#-:-O0EbsI18ahQqQYcy2j8:b-75xhwp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
> Will need some rebasing if Vite PR is merged but looks good

Done!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351#-:-O1XT7qOBQBkY5Yvz9ve:bct9ene)* status: 2 of 13 files reviewed, all discussions resolved (waiting on @dnlnashed, @szczz, and @yileifeng)

**Review by yileifeng — CHANGES_REQUESTED** [review]
Not sure if this was due to rebased changes but getting this behavior on initial load on the help icon (transforms to icon after a few seconds).

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351#-:-O1byfLb4AbueiUlHp2e:biwmnv2)* status: 2 of 13 files reviewed, all discussions resolved (waiting on @dnlnashed and @szczz)

**Review by RyanCoulsonCA — COMMENTED** [review]
I had just moved the source for the material symbols from the Vue component because I was dealing with that same issue. We really don't need to be adding a whole new font just for a question mark so I've removed it entirely and just replaced it with a regular `?`.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351#-:-O1cAnFa47vKfMc9b-N5:badcbiq)* status: 2 of 13 files reviewed, all discussions resolved (waiting on @dnlnashed, @szczz, and @yileifeng)

**Review by yileifeng — APPROVED** [review]
> Reviewed 7 of 11 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dnlnashed and @szczz)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 7 of 11 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/351)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @szczz)

**Pull request merged**
