### PR TITLE
added logging to express server

### LINKED ISSUE #144: Express server logging
If possible, it would be nice if the Express server could output events run against it to a logfile:

- [ ] UUID successfully loaded
- [ ] UUID not found
- [ ] UUID successfully updated
- [ ] Other errors?

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #144 

This PR adds logging to the Express server.

It logs the following, both to the console and to a logfile:
- server initialized
- product loaded
- product failed to load
- product folder uploaded (user saved)
- product folder upload rejected
- file removed from the server (garbage collection)

Example Log:
```
03/22/2023 07:53:09 am [INFO] Storylines Express Server Started, PORT: 6040
03/22/2023 07:54:51 am [INFO] Access attempt to 00000000-0000-0000-0000-000000000q failed, does not exist.
03/22/2023 07:56:11 am [INFO] Successfully loaded product 00000000-0000-0000-0000-000000000000
03/22/2023 07:56:22 am [INFO] Uploaded files to product ./public/00000000-0000-0000-0000-000000000000
03/22/2023 07:56:27 am [INFO] Uploaded files to product ./public/00000000-0000-0000-0000-000000000000
03/22/2023 07:56:27 am [WARNING] Removing assets/en/image.jpg because it no longer exists in the product.
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146)

### CODE REVIEW

**Review by mohsin-r — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`server/index.js` line 64 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146#-NR9p_Ew6AcXTitB5KfZ:-NR9p_Ew6AcXTitB5Kf_:bb1wjwu) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/404c8287a5453ca868b1673075d8a2ec38f31406/server/index.js#L64)):*
> ```JavaScript
>         // Before unzipping, create the product folder in /public/ if it doesn't exist already.
>         if (!fs.existsSync(fileName)) {
>             fs.mkdirSync(fileName);
> ```

Maybe it could be nice to add a log here saying "Successfully created new product [UUID]".

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mohsin-r)

___
*[`server/index.js` line 64 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146#-NR9p_Ew6AcXTitB5KfZ:-NR9rqb32YhGm131cska:b-896fja) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/404c8287a5453ca868b1673075d8a2ec38f31406/server/index.js#L64)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

Maybe it could be nice to add a log here saying "Successfully created new product [UUID]".
</blockquote></details>

Done!

**Review by yileifeng — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by roryhofland — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
