### PR TITLE
add support for external logo URLs

### LINKED ISSUE #80: Enable logo preview for external URLs
Currently (as of #74 being merged) only logos that are saved locally will load properly. Add additional functionality to support external URLs (like what the `00000000-0000-0000-0000-000000000000` product uses for its logo).

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #80 

This PR allows you to use an external URL as a source for the logo. When loading the metadata page, it will attempt to fetch and display this logo if the URL is valid.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85)

### CODE REVIEW

**Review by mohsin-r — CHANGES_REQUESTED** [review]
Not sure if I'm doing something wrong, but when I create a new storyline, put in an image URL in the logo input, and then save the storyline, it saves as `uid/assets/en/undefined` instead of the URL. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85#-:-NOKWEIXDdp1mUzioCam:bzh34vz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
Good catch, I forgot to add the code to set the source when creating a new product. Should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85#-:-NOK_Aup0qt8ZUElHzQ7:b-kfmfoz)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by mohsin-r — APPROVED** [review]
Looks good now! Another thing that could be nice to have is that changing the URL input field instantly shows the new preview, and if a preview can't be displayed, an error message saying "Invalid image URL" or something appears.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85#-:-NOKn1_s9LRNLreT6bkB:btbyw2m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
Good idea, I've added that now. The image preview is replaced with an error message if the image doesn't exist, or if a CORS error occurs.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85#-:-NOLWuHWCVZf3DJ2LZ3F:blp2kao)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
