### PR TITLE
add slide copying

### LINKED ISSUE #8: Implement "Copy existing" feature
- Select (via dropdown?) an existing slide
- Clone the configuration into a new slide in the main JSON structure
- Also clone the RAMP/Highcharts configs as necessary
- (Optional?) Pull from existing product in another folder

### PR DESCRIPTION
**Pull request by spencerwahl**
Closes #8

Copies slides using a deep clone so changes wont affect eachother.

On config load all sources are parsed and counted for the purpose of only deleting files from the zip when they are actually no longer in use.

Counts are tracked through source additions/removals, when the count hits 0 from a removal then the file is removed from the zip.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
Needs a rebase

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-:-NNvwSTJ5Om1wndIzg8R:b-7blfmd)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[`src/components/editor/chart-editor.vue` line 147 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-NNvwdet5Xstm2HQvGjh:-NNvwdet5Xstm2HQvGji:brrudgq) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/08b813f82570596eaa870b44fe099d8ae3c87b94/src/components/editor/chart-editor.vue#L147)):*
> ```Vue
>             }
> 
>             if (this.sourceCounts[`${this.configFileStructure.uuid}/charts/en/${chartInfo.newChart.name}.json`]) {
> ```

store this string as a variable for readability?

**Review by RyanCoulsonCA — COMMENTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[`src/components/editor/editor.vue` line 56 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-NNvxeduCGMY_eI0u_tq:-NNvxeduCGMY_eI0u_tr:bnrxa0b) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/08b813f82570596eaa870b44fe099d8ae3c87b94/src/components/editor/editor.vue#L56)):*
> ```Vue
>                     :lang="lang"
>                     :uid="uuid"
>                     :sourceCounts="sourceCounts"
> ```

If we want to avoid having more props, this can always be included in the [`configFileStructure` object](https://github.com/ramp4-pcar4/storylines-editor/blob/dd5ac3f040e8fafd07a3d37389712b52e65e2809/src/components/editor/editor.vue#L186) since that's passed in to most components already. Doesn't really matter much at the end of the day though

**Review by spencerwahl — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-:-NOKfxFB8N91vQynVhro:bb7f2mf)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

___
*[`src/components/editor/chart-editor.vue` line 147 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-NNvwdet5Xstm2HQvGjh:-NOKfzKm2F1RZlYi_Idq:b-896fix) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/08b813f82570596eaa870b44fe099d8ae3c87b94/src/components/editor/chart-editor.vue#L147)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

store this string as a variable for readability?
</blockquote></details>

Done.
___
*[`src/components/editor/editor.vue` line 56 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-NNvxeduCGMY_eI0u_tq:-NOKg-8N3EksISeGsvcN:b-rhabej) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/08b813f82570596eaa870b44fe099d8ae3c87b94/src/components/editor/editor.vue#L56)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

If we want to avoid having more props, this can always be included in the [`configFileStructure` object](https://github.com/ramp4-pcar4/storylines-editor/blob/dd5ac3f040e8fafd07a3d37389712b52e65e2809/src/components/editor/editor.vue#L186) since that's passed in to most components already. Doesn't really matter much at the end of the day though
</blockquote></details>

I've left it out for now as to me its clearer what goes where rather than putting everything in one object :shrug: .

**Review by spencerwahl — COMMENTED** [review]
Something seems like it went wrong with the rebase yesterday... fixing

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-:-NOPhn8Y1WWvN0GIoSJ1:br55o25)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @yileifeng)

**Review by spencerwahl — COMMENTED** [review]
Building properly now :heavy_check_mark: 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/67#-:-NOQkH7Y-n5_ufGnzCET:b-92g756)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @yileifeng)

**Pull request closed without merging**
