### PR TITLE
Dashboard Redesign

### PR DESCRIPTION
**Pull request by IshavSohal**
### Related Item(s)
#373

### Changes
- Redesigned the dashboard based on the mockups from the UI/UX team

### Testing
Steps:
1. Open the app and select any language
2. Observe the dashboard

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)

### CODE REVIEW

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
Looks good, very nice work! I just have a few suggestions/ideas below.

This will also act as a blocker until we remove the temporary stuff (previously edited products, `Hello Test User`, etc).

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-:-O6S1YMw3RK4Gm4UGTMv:btqn7sf)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/home.vue` line 4 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S232068RFxp2C0Z3f:-O6S232068RFxp2C0Z3g:b5wki87) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L4)):*
> ```Vue
>     <div>
>         <div class="flex justify-between items-center p-8 border-b border-solid border-black">
>             <h1 class="text-4xl">RAMP Storylines Editor & Creation Tool</h1>
> ```

Translation needed here.
___
*[`src/components/home.vue` line 5 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S3biX9ESUvyGbmKLw:-O6S3biX9ESUvyGbmKLx:b-942kze) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L5)):*
> ```Vue
>         <div class="flex justify-between items-center p-8 border-b border-solid border-black">
>             <h1 class="text-4xl">RAMP Storylines Editor & Creation Tool</h1>
>             <div class="underline">{{ $t('editor.lang.curr') }}</div>
> ```

We'll need the language switch to be functional before merging.
___
*[`src/components/home.vue` line 15 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S3Q1e9RI89SV5rswy:-O6S3Q1e9RI89SV5rswz:baftc62) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L15)):*
> ```Vue
>             <div class="mb-5 text-2xl font-semibold">{{ $t('editor.chooseOption') }}</div>
>             <div class="flex justify-center">
>                 <div class="home-btn-container border border-gray-400 border-solid mr-5 create-product">
> ```

This is fine as is, but just as a personal preference it feels more aesthetically pleasing to me to have these buttons take up the full width of the container like they've done in the mockups:



Should be as easy as adding the `flex-1` class to both this div and the `load existing` div just below this one. Open to feedback here!
___
*[`src/components/home.vue` line 31 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S1GyY2wUX182kjWy1:-O6S1GyY2wUX182kjWy2:bp6m2yy) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L31)):*
> ```Vue
>                             </svg>
>                             <span>{{ $t('editor.createProduct') }}</span>
>                             <span class="hidden"> {{ $t('editor.createProductHover') }}</span>
> ```

We probably don't need the text to change here on hover, it seems a bit jarring. I see that they've done that in the Figma mockup but I'm assuming it's just a mistake. Pretty sure they just wanted to show the hover styling on the button here.
___
*[`src/components/home.vue` line 135 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S29Cv2WUFhoGfGqNl:-O6S29Cv2WUFhoGfGqNm:b5wki87) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L135)):*
> ```Vue
>                                 </svg>
>                             </span>
>                             <span>Edit</span>
> ```

Translation needed here.
___
*[`src/lang/lang.csv` line 28 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S5CMP3Ohf3Kx3eLCT:-O6S5CMQ5nkKqaAsD25c:b-bxn2zm) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/lang/lang.csv#L28)):*
> ```CSV
> editor.lang.en,English,1,Anglais,1
> editor.lang.fr,French,1,Français,1
> editor.lang.curr,English,1,Français,1
> ```

Clever use of translations here, but we should probably just use the individual translations for English and French as this could get confusing in the future.

**Review by IshavSohal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/home.vue` line 4 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S232068RFxp2C0Z3f:-O6beh4V9CPg-ZYiai4l:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L4)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Translation needed here.
</blockquote></details>

Donethanks
___
*[`src/components/home.vue` line 5 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S3biX9ESUvyGbmKLw:-O6beix37ezayj23B23O:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L5)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

We'll need the language switch to be functional before merging.
</blockquote></details>

Donethanks
___
*[`src/components/home.vue` line 15 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S3Q1e9RI89SV5rswy:-O6bekaVAd2pnuo4yzJ1:b-brs3io) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L15)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This is fine as is, but just as a personal preference it feels more aesthetically pleasing to me to have these buttons take up the full width of the container like they've done in the mockups:



Should be as easy as adding the `flex-1` class to both this div and the `load existing` div just below this one. Open to feedback here!
</blockquote></details>

I've made the change and I agree, it definitely looks more appealing. 
___
*[`src/components/home.vue` line 31 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S1GyY2wUX182kjWy1:-O6bewt_B_jW9NxslxLl:bejc8w7) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L31)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

We probably don't need the text to change here on hover, it seems a bit jarring. I see that they've done that in the Figma mockup but I'm assuming it's just a mistake. Pretty sure they just wanted to show the hover styling on the button here.
</blockquote></details>

That makes sense, I've removed it. I've also included the hover styling on the other buttons
___
*[`src/components/home.vue` line 135 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S29Cv2WUFhoGfGqNl:-O6bf5PG9LNgXaOo-8sO:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/components/home.vue#L135)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Translation needed here.
</blockquote></details>

Donethanks
___
*[`src/lang/lang.csv` line 28 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O6S5CMP3Ohf3Kx3eLCT:-O6bf6eD5x1QAljWVClD:bo8395a) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2e7d3c70ad8f478a4ecbe85efbdf742027fe2705/src/lang/lang.csv#L28)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Clever use of translations here, but we should probably just use the individual translations for English and French as this could get confusing in the future.
</blockquote></details>

Donethanks, I've also removed it from the lang csv

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/home.vue` line 6 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70AmBp2_W30bfNWz2I:-O70AmBp2_W30bfNWz2J:byt2ke7) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L6)):*
> ```Vue
>             <h1 class="text-4xl">{{ $t('editor.respectTitle') }}</h1>
>             <router-link :to="{name: 'home', params: { lang: currLang === 'en' ? 'fr' : 'en' }}">
>                 <div class="underline">{{ $t(`editor.lang.${currLang}`) }}</div>
> ```

Switching the langauge works well, but the text is currently showing the language that you're currently using instead of the language you're switching to. If you're using English, we want this to say `Francais`, and if you're using French we want this to say English.
___
*[`src/components/home.vue` line 157 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70BdEkE0DLDiatpPsi:-O70BdEl1ZGTIFDlXmyp:bh5zngh) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L157)):*
> ```Vue
>         this.currLang = (this.$route.params.lang as string) || 'en';
>         // just for testing purposes
>         this.userStore.userProfile.userName = 'Test User';
> ```

Blocking here until we get this part working (unless we decide to merge it before implementing this on the server side)

**Review by IshavSohal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/home.vue` line 6 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70AmBp2_W30bfNWz2I:-O75qiEX0EkyKJ0dgOee:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L6)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Switching the langauge works well, but the text is currently showing the language that you're currently using instead of the language you're switching to. If you're using English, we want this to say `Francais`, and if you're using French we want this to say English.
</blockquote></details>

Donethanks

**Review by yileifeng — CHANGES_REQUESTED** [review]
New UI changes look great :+1:

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-:-O7_cL295UTl07w5pIfv:b-ytu1p2)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

___
*[`src/components/home.vue` line 6 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70AmBp2_W30bfNWz2I:-O7_daMn-qQuBXEQPY-s:b6ogm7k) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L6)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Donethanks
</blockquote></details>

Only render this link when we are not using the Canada.ca template, otherwise will have two instances of language toggle.
___
*[`src/components/home.vue` line 19 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O7_du4xBc1DMB0faj4E:-O7_du4xBc1DMB0faj4F:b-hxktj2) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/98a516e58d619139e392ae6d46b8cb2540928679/src/components/home.vue#L19)):*
> ```Vue
>                 <div class="home-btn-container border border-gray-400 border-solid mr-5 home-buttons flex-1">
>                     <router-link :to="{ name: 'metadataNew' }" class="flex justify-center h-full w-full" target>
>                         <button class="flex items-center text-xl font-bold">
> ```

Using keyboard navigation for the "Create New Storylines Product" and the "Load Existing Storylines Product" requires an additional tab as it focuses the whole container and then focuses the inner label. We would only want to focus one or the other, ideally the entire container.

**Review by IshavSohal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

___
*[`src/components/home.vue` line 6 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70AmBp2_W30bfNWz2I:-O7e_94lCcOryRQljdG7:b6q6lrz) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L6)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Only render this link when we are not using the Canada.ca template, otherwise will have two instances of language toggle.
</blockquote></details>

Donethanks. I created a `template` prop for the home page, and then rendered the link only when its not equal to 'Canada.ca'. Let me know if you have something else in mind. 
___
*[`src/components/home.vue` line 19 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O7_du4xBc1DMB0faj4E:-O7e_Qs04jD7zDu3zAD1:b-k56a2d) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/98a516e58d619139e392ae6d46b8cb2540928679/src/components/home.vue#L19)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Using keyboard navigation for the "Create New Storylines Product" and the "Load Existing Storylines Product" requires an additional tab as it focuses the whole container and then focuses the inner label. We would only want to focus one or the other, ideally the entire container.
</blockquote></details>

Good catch, donethanks. Also fixed a similar issue in the `back` button for the metadata editor.

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

___
*[`src/components/home.vue` line 6 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70AmBp2_W30bfNWz2I:-O7jfg0kA4ndC2KzhQxX:b-vc618c) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L6)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Donethanks. I created a `template` prop for the home page, and then rendered the link only when its not equal to 'Canada.ca'. Let me know if you have something else in mind.
</blockquote></details>

Hmm this strategy will not work since the template gets rendered when we are on the index-ca-en.html or index-ca-fr.html page. For example, following the https://ramp4-pcar4.github.io/storylines-editor/dashboard-redesign/index-ca-en.html#/en/editor demo link will load the Canada template and see the following results with two lang toggles: 



Not sure if there is already an existing check in the codebase for this, but a potential solution(?) for this might be to search for "index-ca-en.html" or "index-ca-fr.html" inside the Vue Router object's URL. Another approach would be to set a flag determining if we are using Canada.ca template inside the Router's meta fields and just have the conditional check on that.

**Comment by IshavSohal** [comment]
*[`src/components/home.vue` line 6 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70AmBp2_W30bfNWz2I:-O88bKX_2gBibjy-E4Po:b-2nhfbf) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L6)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Hmm this strategy will not work since the template gets rendered when we are on the index-ca-en.html or index-ca-fr.html page. For example, following the https://ramp4-pcar4.github.io/storylines-editor/dashboard-redesign/index-ca-en.html#/en/editor demo link will load the Canada template and see the following results with two lang toggles: 



Not sure if there is already an existing check in the codebase for this, but a potential solution(?) for this might be to search for "index-ca-en.html" or "index-ca-fr.html" inside the Vue Router object's URL. Another approach would be to set a flag determining if we are using Canada.ca template inside the Router's meta fields and just have the conditional check on that.
</blockquote></details>

Donethanks, I made it so that the language toggle doesn't render when the current source page is "index-ca-en.html" or "index-ca-fr.html"

**Review by yileifeng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-:-O8Iolas45gG9HBgsF57:bnfp4nl)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

**Review by gordlin — CHANGES_REQUESTED** [review]
Looks pretty good! 

The only issue I noticed was that the page format is completely messed up on mobile:


> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-:-O9GqmzY32hw8pCQ8JgK:b3hcuhs)* status: all files reviewed, 2 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: all files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/home.vue` line 157 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-O70BdEkE0DLDiatpPsi:-O9Kynnm6Xihy9Xhs4NI:b-l1pqtr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/c67ec8e55cc76b4a18fd783769bb33f5d0cf582e/src/components/home.vue#L157)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Blocking here until we get this part working (unless we decide to merge it before implementing this on the server side)
</blockquote></details>

Server side will hopefully be complete next week. Let's hold off for that.

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: all files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

**Comment by IshavSohal** [comment]
Donethanks

**Review by gordlin — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: all files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — APPROVED** [review]
Approving this but we'll keep it open until the server side is finished up.

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389#-:-O9uM_H5Cx9OKHm1sx8b:b9w04j3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Comment by szczz** [comment]
Sorry for the delay, service desk and licensing delays held things up. lastModified date is being returned from the API now. Please proceed with updating the frontend to display the Last Modified date (Most records are set to the time of DB migration, but this will be updated as changes are made to storylines)

**Comment by IshavSohal** [comment]
Donethanks

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 1 of 2 files at r6, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Review by szczz — APPROVED** [review]
> Reviewed 4 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)

**Pull request merged**
