### PR TITLE
Implement git-based version history

### PR DESCRIPTION
**Pull request by mohsin-r**
### Related Item(s)
#421, #189 

### Changes
- [FEATURE] Implemented git-based version history. This is handled entirely by the express server using `git` and we no longer need the .NET API for this (pending design approvals of course).
- Fixed an issue where running the app locally would not show the successfully saved message.
- Fixed an issue where loading a prior version without a logo whereas a current version had the logo would not clear the logo and its preview.

### Notes
**Note 1**: Unfortunately anyone reviewing this PR will need to test locally since there are server changes involved.
**Note 2**: ~~This PR likely breaks any existing storylines products as they are not currently git repos.~~ Any existing storylines products that are not git repos will be returned into git repos upon retrieval.

### Testing
To test this PR thoroughly, I would recommend attempting to create new storylines, get existing storylines, save storylines after making all kinds of changes, load the version history, attempt to load a specific version, and attempt to save changes to a specific version. Additionally if you'd like, feel free to `cd` into your storyline's folder and run `git log` commands on the command prompt to ensure that everything works as expected.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422)

### CODE REVIEW

**Review by IshavSohal — COMMENTED** [review]
There seems to be an issue when trying to branch off of an older commit

1. Create a new product, fill in metadata and click `Next`
2. Make a change and click `Save Changes`
3. Go back to metadata editor and load in the product
4. Click 'View Previous' and select the initial version
5. Click `Next`
6. Make a change and click `Save Changes`
7. Observe that the save fails, and the server throws an error:
`GitError: error: pathspec 'main' did not match any file(s) known to git`
8. Restart the server, go back to the metadata editor, and load the product again
9. Click `Next`
10. Make another change and click `Save Changes`
11. Observe that the save succeeds this time

I'm also able to reproduce this when loading in an existing product that doesn't have a git repo.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422#-:-OC5QVSt9ZzCS3s4k07U:b-vtlz62)* status: 0 of 8 files reviewed, all discussions resolved

**Review by mohsin-r — COMMENTED** [review]
Hmmmm I spent a fair bit of time trying to reproduce this but it seemed to work every time. Not sure what is happening. Out of curiosity was this happening locally or on the .NET deployment?

Anyways one thing I have done as an attempt is to disable the next button until the storyline is fully loaded.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422#-:-OCDpGoc5z8uoVRntbhg:b-ep8prm)* status: 0 of 8 files reviewed, all discussions resolved

**Review by mohsin-r — COMMENTED** [review]
Ok I think I figured it out. I think its because your default branch is not `main` and the code was assuming the default as `main`. It should be fixed now, thanks for the catch!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422#-:-OCDyK9U4tsHcEejUSuC:b-vwwuth)* status: 0 of 8 files reviewed, all discussions resolved

**Review by szczz — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422)* status: all files reviewed, 1 unresolved discussion (waiting on @mohsin-r)

___
*[`server/index.js` line 169 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422#-OCDysWe3UwukD-8lvpq:-OCDysWe3UwukD-8lvpr:b13yvog) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/fed408d2cf91fe7926e6a3e0122a7ab26f76df27/server/index.js#L169)):*
> ```JavaScript
> 
> // GET requests made to /retrieve/ID/commitHash will be handled here.
> // Callimg this with commitHash as "latest" simply fetches the product as normal.
> ```

Callimg

**Review by mohsin-r — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @szczz)

___
*[`server/index.js` line 169 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422#-OCDysWe3UwukD-8lvpq:-OCJdsUH2SHGeX29Ydiy:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/fed408d2cf91fe7926e6a3e0122a7ab26f76df27/server/index.js#L169)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Callimg
</blockquote></details>

Donethanks.

**Review by RyanCoulsonCA — APPROVED** [review]
Server code looks good to me! I also tested creating a new product and loading existing products both locally and on the dev site and haven't run into any obvious issues.

> Reviewed 3 of 8 files at r1, 1 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422#-:-OCKCPoKBsuaUaxwemKM:b-elzcri)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/422)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Pull request merged**
