### PR TITLE
Integrate config editor into RESPECT

### LINKED ISSUE #246: Package the config-editor to auto-build with RESPECT
Package the [Mohsin-config-editor](https://github.com/ramp4-pcar4/config-editor/issues) into the Storylines Editor build process, so the latest version is grabbed and used when the Editor is built.

### LINKED ISSUE #256: Saving and integrating the config-editor
@tosellob's review revealed the awkward symptom of having "apps within an app" when it comes to map configurations. 

In the current "FGPA" workflow, the user creates a map-type slide, gives the map config a filename, and the FGPA tool opens. The user must actively SAVE the file within RESPECT, in addition to saving the Storylines product itself. This is confusing, as the user doesn't understand what's being saved and where with regards to the RAMP configs.

We have an opportunity to modify this workflow this as we switch to the Mohsin-Editor:
- Setting RAMP config filenames is basically meaningless to the user. Perhaps we can standardize this and remove the option to name them entirely?
- Do we need an "internal" save button with the config editor, or should we go with a "save-as-you-edit" approach?

Related #239.

### PR DESCRIPTION
**Pull request by mohsin-r**
### Related Item(s)
Closes #246.
Closes #256.

### Changes
- Replaced FGP Authoring Tool with the [config editor](https://github.com/ramp4-pcar4/config-editor).
- Created [NPM package](https://www.npmjs.com/package/ramp-config-editor_editeur-config-pcar) for the config editor.
- Refactored styling across the app.

### Notes
This PR results in breaking changes, namely the map panel for any existing products with RAMP2 configs in them will no longer work. The rest of the editor should work, however.
Additionally, maps don't work when you preview the whole product. This has been logged in the [storylines repo](https://github.com/ramp4-pcar4/story-ramp/issues/415). For now, maps can be previewed using the preview functionality in the config editor.
Also, the options section in the config editor cannot be saved. This is because our current storylines schema doesn't support it, so I didn't save it anywhere. Just in case someone grouses that's a bug.

### Testing
Steps:
1. Open the storylines editor.
2. Attempt to create, load, and save maps with different configurations.
3. Grouse if something doesn't work. Since styling was refactored, a quick look at overall styling would also be appreciated.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
Nice work :trophy: 

Looks like the preview mode styling needs to be fixed. Might need to modify the tailwind configuration is my initial guess. 

> Reviewed 1 of 230 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-:-NtbX8nQ9Ezl7CJu5i-m:bdel3hp)* status: 1 of 230 files reviewed, 4 unresolved discussions (waiting on @mohsin-r)

___
*[`public/help/en.md` line 91 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbUf9s1s-UVT1_xun3:-NtbUf9t0L4oeV3_3s8P:b-r1gdmv) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/public/help/en.md#L91)):*
> ```Markdown
> | The icon representing the Toggle Visibility function | Toggle Visibility | Enables or disables the visibility for all layers |
> ```

There is an updated version of the RAMP help docs
___
*[`src/components/editor/metadata-editor.vue` line 10 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbYjUpDVK6RVoW_oN3:-NtbYjUpDVK6RVoW_oN4:b-vvnyn6) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/src/components/editor/metadata-editor.vue#L10)):*
> ```Vue
>                         {{ editExisting ? $t('editor.editProduct') : $t('editor.createProduct') }}
>                     </div>
>                     <button class="editor-button" @click="swapLang()">
> ```

This button should be right-aligned on the metadata page
___
*[`src/components/editor/metadata-editor.vue` line 83 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbWLyiCLVxYgujlXtq:-NtbWLyiCLVxYgujlXtr:b-w9tv8w) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/src/components/editor/metadata-editor.vue#L83)):*
> ```Vue
> 
>             <div class="flex mt-8">
>                 <button v-if="editExisting" @click="saveMetadata(true)" class="editor-button pl-8">
> ```

Remove "pl-8"
___
*[`src/components/editor/metadata-editor.vue` line 92 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbWQGtBeqCn2IQTJiu:-NtbWQGtBeqCn2IQTJiv:b-w9m7ek) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/src/components/editor/metadata-editor.vue#L92)):*
> ```Vue
>                     <button
>                         @click="!warning ? continueToEditor() : $vfm.open(`confirm-uuid-overwrite`)"
>                         class="editor-button bg-black text-white px-8"
> ```

Remove "px-8"

**Review by mohsin-r — COMMENTED** [review]
Donethanks by updating to the latest storylines package. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-:-Nu4aF43-qKRw95Wbt_r:bbyue08)* status: 0 of 232 files reviewed, 4 unresolved discussions (waiting on @yileifeng)

___
*[`public/help/en.md` line 91 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbUf9s1s-UVT1_xun3:-Nu4aS5Z2IcMsR5Hn9Ee:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/public/help/en.md#L91)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

There is an updated version of the RAMP help docs
</blockquote></details>

Donethanks.
___
*[`src/components/editor/metadata-editor.vue` line 10 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbYjUpDVK6RVoW_oN3:-Nu4aXQN5KIJOGLgOFI0:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/src/components/editor/metadata-editor.vue#L10)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

This button should be right-aligned on the metadata page
</blockquote></details>

Donethanks.
___
*[`src/components/editor/metadata-editor.vue` line 83 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbWLyiCLVxYgujlXtq:-Nu4aYWZ8E0LnR5wRKD9:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/src/components/editor/metadata-editor.vue#L83)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Remove "pl-8"
</blockquote></details>

Donethanks.
___
*[`src/components/editor/metadata-editor.vue` line 92 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-NtbWQGtBeqCn2IQTJiu:-Nu4a_Ew5wi2Qsp_m54S:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/39825f6904a68b696817814e804e13ab578a5d78/src/components/editor/metadata-editor.vue#L92)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Remove "px-8"
</blockquote></details>

Donethanks.

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
Looks really good, awesome work! 

A couple of things:
1. The preview seems to break when you modify the starting fixtures. I tried to remove the `export` fixture and when I pressed preview, the map loaded but the fixtures did not. It also seems like extra spaces are added in between the list items when you make changes to it. When I save the product and look at the config the array looks like this, so stripping probably has to be done somewhere:
```
"startingFixtures": [
  "geosearch",
  " overviewmap",
  " basemap",
  ...
],
```
2. When using RESPECT in French, the map editor remains in English.

> Reviewed 222 of 230 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-:-Nu_6ra04VBLchke99-R:b-jufkr2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by mohsin-r — COMMENTED** [review]
1. This should be fixed now. Thanks for the catch!
2. Dan mentioned that French translations for the config editor are not urgent and it can remain in English for now. However, I do agree that we should at least have the [FR] placeholder appended to English text. Since this will take a while to do, I think it would be better to make a new issue for this, as opposed to adding it in this PR. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-:-NvCjvEe9ErJx4YDTpfN:b-psqcl7)* status: 220 of 232 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA and @yileifeng)

**Review by yileifeng — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by RyanCoulsonCA — APPROVED** [review]
Sounds good to me!

> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271#-:-NvDh9a91uw836ZBfEj9:b-ba7jdc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 216 of 230 files at r1, 4 of 10 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/271)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)

**Pull request merged**
