### PR TITLE
Upgrade build from Vue CLI to Vite

### LINKED ISSUE #238: Upgrade Vue CLI to Vite
Same as https://github.com/ramp4-pcar4/story-ramp/issues/381

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
Closes #238 

### Changes
- Upgraded Vue CLI toolchain to Vite
- Moved all files from public folder to root
- Changed all `require` statements to `import`
- Resolved all conflicting package dependencies + TS errors
- Updated ENV variables 
- Added changes to support integration of #290 

### Notes
Needed to add an additional dependency `url` to access the `resolve` function of `jsonschema` validation, there seems to be a PR to fix the issue in the GitHub repository but https://www.npmjs.com/package/jsonschema NPM package has not been updated. 

`npm run dev` is new command to run project locally for development. 

On final note, will require some changes to accommodate for https://github.com/ramp4-pcar4/storylines-editor/pull/290 when it gets merged. 

### Testing
All editor functionality, files, routes, components to be working correctly 🙏

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)

### CODE REVIEW

**Comment by yileifeng** [comment]
In the process of integrating #290 changes

**Comment by yileifeng** [comment]
Finished updating and added support for #290

**Review by james-rae — CHANGES_REQUESTED** [review]
> Reviewed 3 of 65 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: 3 of 65 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`README.md` line 3 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-NxxYlG935dY89Gy8PHC:-NxxYlGAAzyFu2sz2fnz:b-jgged9) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/8642d144fd30175d077d64ddf4cc1b6f2f2faa39/README.md#L3)):*
> ```Markdown
> # RAMP Storylines Editor
> 
> This project is an implementation of [RAMP2 FGP Visualiser](https://github.com/fgpv-vpgf/fgpv-vpgf), [Highcharts](https://www.highcharts.com/), and a number of other libraries, with the goal to provide a standards and guidelines compliant alternative to ArcGIS StoryMap, suitable for use in the Government of Canada's web presence. 
> ```

This part is still kinda wrong. Ramp2, and makes it sound like its Storylines and not the Editor.
Won't block, can spin into a new issue
___
*[`src/lang/lang.csv` line 27 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-NxxZ1QHEx-Xoo1uRJaJ:-NxxZ1QHEx-Xoo1uRJaK:b5ztv24) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/8642d144fd30175d077d64ddf4cc1b6f2f2faa39/src/lang/lang.csv#L27)):*
> ```CSV
> editor.feedback.subject,Storylines Editor Feedback,1,Commentaires de l'éditeur de scénarios,0
> editor.window.title,RAMP Storylines Editor,1,Éditeur de scénarios de la PCAR,1
> editor.configOverwrite,Are you sure you want to overwrite product '{uuid}'?,1,[FR] Are you sure you want to overwrite product '{uuid}'?,0
> ```

If this is going "live" (it's `main` so ??), or we can't guarantee we have official translation patch before going live, these unofficial ones should be google-translated for now. Won't be perfect but better for a French-reading user than English placeholders. If too big a change (quite a few in this file) spin into new issue so you can get this big PR done and I'll unblock.

**Review by yileifeng — COMMENTED** [review]
> Reviewed 45 of 65 files at r1, 20 of 20 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[`README.md` line 3 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-NxxYlG935dY89Gy8PHC:-Nxxk4Mf2XW90QIyhkMA:buda5nw) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/8642d144fd30175d077d64ddf4cc1b6f2f2faa39/README.md#L3)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

This part is still kinda wrong. Ramp2, and makes it sound like its Storylines and not the Editor.
Won't block, can spin into a new issue
</blockquote></details>

Made an issue in #286 
___
*[`src/lang/lang.csv` line 27 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-NxxZ1QHEx-Xoo1uRJaJ:-NxxkIXR7jpTXELb2N3C:bv40prj) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/8642d144fd30175d077d64ddf4cc1b6f2f2faa39/src/lang/lang.csv#L27)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

If this is going "live" (it's `main` so ??), or we can't guarantee we have official translation patch before going live, these unofficial ones should be google-translated for now. Won't be perfect but better for a French-reading user than English placeholders. If too big a change (quite a few in this file) spin into new issue so you can get this big PR done and I'll unblock.
</blockquote></details>

Added temp FR translations

**Review by james-rae — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

___
*[`src/lang/lang.csv` line 27 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-NxxZ1QHEx-Xoo1uRJaJ:-NxxlVPI-ILAZ4ceVW3v:b-83olaz) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/8642d144fd30175d077d64ddf4cc1b6f2f2faa39/src/lang/lang.csv#L27)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Added temp FR translations
</blockquote></details>

Noice

**Review by yileifeng — COMMENTED** [review]
Good catch, the issue seems to be with how `npm run build` constructs the dist folder contents with Vite. Other scripts such as the highcharts editor also are not working on the prod build whereas everything works locally with `npm run dev`. Will take some time to look into this.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-:-NyvGCTV3tHyhm642Zyp:b-410nhu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Building for prod issues should be fixed now (highcharts editor + help contents) and everything should be ready for testing. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-:-O-qnbK5C9-sExLqL7Q9:b6iwibo)* status: 50 of 69 files reviewed, all discussions resolved (waiting on @james-rae and @RyanCoulsonCA)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 17 of 19 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — CHANGES_REQUESTED** [review]
Before this is merged please let me know and I'll update the pipelines to match the new env variables.

> Reviewed 40 of 65 files at r1, 10 of 20 files at r5, 17 of 19 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-:-O0yEqwnEwMKrUMkIATq:b-q0pszr)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`src/app.vue` line 24 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-O0yESNsAatrzCohN3pb:-O0yESNsAatrzCohN3pc:bxvswz2) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7329817649e70b53a33ba3c0feb3db619543e388/src/app.vue#L24)):*
> ```Vue
>         const userStore = useUserStore(this.$pinia);
>         // We can mock the user's profile for local development here if needed.
>         if (import.meta.env.VITE_APP_CURR_ENV && import.meta.env.VITE_APP_CURR_ENV !== '#{CURR_ENV}#') {
> ```

Can this be imported once?

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: 62 of 69 files reviewed, 1 unresolved discussion (waiting on @dnlnashed, @RyanCoulsonCA, and @szczz)

___
*[`src/app.vue` line 24 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295#-O0yESNsAatrzCohN3pb:-O1Hm7EXEtTU1EIwvfQQ:b-nakr8h) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7329817649e70b53a33ba3c0feb3db619543e388/src/app.vue#L24)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Can this be imported once?
</blockquote></details>

Removed all instances of `import.meta.env.VITE_APP_CURR_ENV !== '#{CURR_ENV}#'` in non-server files.

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by james-rae — APPROVED** [review]
> Reviewed 40 of 65 files at r1, 8 of 20 files at r5, 12 of 19 files at r6, 2 of 2 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by yileifeng — COMMENTED** [review]
> Reviewed 12 of 19 files at r6, 2 of 2 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: all files reviewed, 1 unresolved discussion (waiting on @szczz)

**Review by szczz — APPROVED** [review]
> Reviewed 7 of 7 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
