### PR TITLE
Add support for advanced/custom config editor

### LINKED ISSUE #190: More granular access to JSON files - Advanced Editor
One conflict our users are running into using the Editor in a remote environment, is that they no longer have access to the file system for making direct changes to the JSON configuration files. This feature could potentially bridge the gap for users who use Visual Studio Code + file system access to edit their products.  

Areas of consideration:
- Allowing the user to edit the entire JSON file for the Storylines product (`_en`, and `_fr`)
- Allowing the user to edit a Highcharts configuration directly
- Allowing the user to edit a RAMP configuration file directly
- Can we integrate some sort of JSON lint integrity check to verify they didn't break the structure?

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
Closes #190
Related to #247 

### Changes
- [FEATURE] Adds JSON editor tab for slides to manually edit configuration
- [FEATURE] Adds JSON schema validation when saving JSON editor and properly updates config
- [FIX] Update missing panel properties for schema
- [FIX] Update 0000 test product to adapt to new dynamic slideshow schema structure

### Testing (in progress)
Any testing involving the custom ("advanced") editor by modifying/adding new config properties for slides and attempting to save. As an example, adding "customStyles": "text-align: center;" to a text panel should apply changes.

If the schema validation error alert is encountered upon saving, it is possible the schema requires more adjustments for missing/outdated properties (NOTE: likely to fail if using custom editor to add niche chart properties or RAMP configuration since those are not contained in panel schema, but in these cases the user should be using the highcharts editor or RAMP config editor respectively).

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
Looks good! We should create a new issue to update the schema to support some of the newer features that have been merged in recently.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280#-:-Nvb75Th1XzIC4F_ojQF:bmtb7n8)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`src/components/editor/helpers/custom-editor.vue` line 3 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280#-Nvb61zv7gIxuJ-KiUo0:-Nvb61zv7gIxuJ-KiUo1:blx5sp5) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/a4997ba2cf74e6699745cd7ee38b8de57a888c1f/src/components/editor/helpers/custom-editor.vue#L3)):*
> ```Vue
> <template>
>     <div class="mt-4">
>         <json-editor
> ```

Is it possible to make the height of the JSON editor slightly taller? It's quite small when I try to use it on my laptop, and there's still some space to show more

**Review by yileifeng — COMMENTED** [review]
Made a new issue to track future schema changes and added a few minor adjustments for current validation errors as discussed

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280#-:-NvbTb_RETzahlyn525n:b-uzalhd)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/editor/helpers/custom-editor.vue` line 3 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280#-Nvb61zv7gIxuJ-KiUo0:-NvbT_RW5aThqdogw3HK:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/a4997ba2cf74e6699745cd7ee38b8de57a888c1f/src/components/editor/helpers/custom-editor.vue#L3)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Is it possible to make the height of the JSON editor slightly taller? It's quite small when I try to use it on my laptop, and there's still some space to show more


</blockquote></details>

Donethanks

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by mohsin-r — APPROVED** [review]
Looks slick! 

One minor grouse I had was the advanced editor save button that asks the user for confirmation before overwriting is way down at the bottom and a user may not see it.

Instead, they may click the regular top right save button, which does not ask for any confirmation and proceeds to save. Not a blocking comment since this is not anything breaking.

> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280#-:-NvpvAf18c09K0X8zNLl:b2aj343)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by KashishMistry — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 3 of 13 files at r1, 1 of 2 files at r2, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by mohsin-r — APPROVED** [review]
Whoops, realized I may have been holding up this PR. 
Looks ALL GOOD!

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/280#-:-NwkCMzM8nB54iCYbWf_:b-fuii0g)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
