### PR TITLE
add feedback button in footer

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Related Item(s)
#293 

### Changes
- Adds a link to the bottom of the editor to provide feedback through email.

### Testing
Steps:
1. Open the demo page.
2. Ensure the "Send us feedback" button is displaying and working properly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297)

### CODE REVIEW

**Review by james-rae — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/editor/editor.vue` line 133 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSp7f96P8Jg0A67Xy7:-NxSp7fA9laTN_-qnQbx:b-wf6siw) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/components/editor/editor.vue#L133)):*
> ```Vue
>         <div class="footer text-right pr-5 editor-button">
>             <a
>                 href="mailto:applicationsdecartographieweb-webmappingapplications@ec.gc.ca?subject=Storylines Editor Feedback"
> ```

You might need to have the `subject=` content also run through the translation module
___
*[`src/lang/lang.csv` line 24 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSpFPK494Ylr0UN1ho:-NxSpFPK494Ylr0UN1hp:b-yb1j5) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L24)):*
> ```CSV
> fullscreen.activate,Enter Fullscreen,1,Afficher le mode plein écran,1
> fullscreen.deactivate,Exit Fullscreen,1,Quitter le mode plein écran,1
> editor.feedback,Send Us Feedback,1,[FR] Send Us Feedback,0
> ```

Google-translated marked as 0 is prob better than the FR, unless the project has a translations update planned before this goes live. If `main` is "live" then would suggest changing to unofficial text in French.

**Comment by james-rae** [comment]
*[`src/lang/lang.csv` line 6 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSr9lA8I4zL2dekAHB:-NxSr9lA8I4zL2dekAHC:bn80vzq) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L6)):*
> ```CSV
> chapters.menu,Toggle menu,1,Menu à bascule,1
> scrollguard.desc,Use ctrl + scroll to zoom the map,1,Utilisez les touches Ctrl et + pour faire un zoom de la carte,1
> story.window.title,RAMP Storylines,1,RAMP Storylines,0
> ```

now i'm causing problems elsewhere.
not official but I've found two other "official" translations of Storylines, both different lol.
Marketing site calls it `Scénarios`.  An error message in Storylines lang file calls it `Synopsis`. 
And `RAMP` would becomes `PCAR`, that one I'm confident on :muscle:

**Comment by james-rae** [comment]
*[`src/lang/lang.csv` line 31 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSxjIBAk8VhdtjFcJ2:-NxSxjIBAk8VhdtjFcJ3:b1f5th1) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L31)):*
> ```CSV
> editor.productDetails,Storylines product details,1,Détails du produit de scénarios,1
> editor.metadata.instructions,Fill in metadata details about your new Storylines product. Use the "Preview" button to see what your slides will look like.,1,Inscrivez les métadonnées de votre nouveau produit de scénario. Utilisez la fonction « Afficher l’aperçu » pour voir à quoi ressemblent vos diapositives.,1
> editor.uuid,UUID,1,UUID,0
> ```

line below suggests `IDUU` is official French.

**Comment by james-rae** [comment]
*[`src/lang/lang.csv` line 6 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSr9lA8I4zL2dekAHB:-NxSy4AL7c7V6HKPXlvh:b83kp6p) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L6)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

now i'm causing problems elsewhere.
not official but I've found two other "official" translations of Storylines, both different lol.
Marketing site calls it `Scénarios`.  An error message in Storylines lang file calls it `Synopsis`. 
And `RAMP` would becomes `PCAR`, that one I'm confident on :muscle:
</blockquote></details>

The `editor.*` keys in the file below all use `Scénarios`

**Comment by james-rae** [comment]
*[`src/lang/lang.csv` line 6 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSr9lA8I4zL2dekAHB:-NxSyJwW8kSmptf0EWul:bpl68cd) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L6)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

The `editor.*` keys in the file below all use `Scénarios`
</blockquote></details>

and `story.error` two lines below is using `synopsis`.  So maybe have a vote next project meeting.

**Review by RyanCoulsonCA — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @james-rae)

___
*[`src/components/editor/editor.vue` line 133 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSp7f96P8Jg0A67Xy7:-NxTkQAjBiINnFRRznfK:b-896fja) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/components/editor/editor.vue#L133)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

You might need to have the `subject=` content also run through the translation module
</blockquote></details>

Done!
___
*[`src/lang/lang.csv` line 6 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSr9lA8I4zL2dekAHB:-NxTk4og2-oQcVH4TPFV:b-pqvq78) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L6)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

and `story.error` two lines below is using `synopsis`.  So maybe have a vote next project meeting.
</blockquote></details>

I'm 99% sure it should be scénarios. I only see `synopsis` being used in one translation, so I've replaced it.
___
*[`src/lang/lang.csv` line 24 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSpFPK494Ylr0UN1ho:-NxTk2i2-tgQFIQnCpPN:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L24)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Google-translated marked as 0 is prob better than the FR, unless the project has a translations update planned before this goes live. If `main` is "live" then would suggest changing to unofficial text in French.
</blockquote></details>

Donethanks.
___
*[`src/lang/lang.csv` line 31 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297#-NxSxjIBAk8VhdtjFcJ2:-NxTk4531e5b8JgMlJOn:b-896fix) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/7b6df9ea93e002d186b332eec98c7beed9619b27/src/lang/lang.csv#L31)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

line below suggests `IDUU` is official French.
</blockquote></details>

Done.

**Review by james-rae — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/297)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
