### PR TITLE
add ability to change product UUID

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
### Related Item(s)
#253 

### Changes
- Adds ability to change the name of existing Storylines products.

### Notes
The old UUID does not automatically get deleted at the moment. We'll need something on the server side to clean this up.

### Testing
Steps:
1. Open the editor and load an existing product.
2. Try to change the name of the product and save it. Ensure the config files are updated correctly and that everything still works.
3. Try to change the name of the product to a UUID that already exists. Ensure that the warning pops up.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
One bug I found was that both warning messages appeared when attempting to rename a product to a UUID to an existing UUID, assuming this is not intended?



> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-:-NxxS4vR9XkvVUqnjokN:bn7cabz)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/editor/metadata-editor.vue` line 918 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-NxxRsio7NzliqzBOvHN:-NxxRsio7NzliqzBOvHO:b877de1) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/55170f031658f7523d4580e4ffb57c005a61e3d3/src/components/editor/metadata-editor.vue#L918)):*
> ```Vue
>     checkUuid(rename?: boolean): void {
>         if (!this.loadExisting || rename) {
>             fetch(`http://localhost:6040/retrieve/${rename ? this.changeUuid : this.uuid}`).then((res: Response) => {
> ```

Might need to be rebased to use the new ENV variables and default to localhost:6040.

**Review by RyanCoulsonCA — COMMENTED** [review]
I think it may be good to keep both warnings up if the user is overwriting another UUID. The two warnings aren't related to each other, and I think it's probably good to inform the user that they'll be overwriting a different product if they proceed.

Open to counter points though!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-:-Ny5g8Ft1sTCKmyOeq8p:b-36lqas)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`src/components/editor/metadata-editor.vue` line 918 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-NxxRsio7NzliqzBOvHN:-Ny5gAQs0nQj5WCNTrs5:b-7v21q8) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/55170f031658f7523d4580e4ffb57c005a61e3d3/src/components/editor/metadata-editor.vue#L918)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Might need to be rebased to use the new ENV variables and default to localhost:6040.
</blockquote></details>

Rebase is done!

**Review by yileifeng — COMMENTED** [review]
In that case, is there a valid use case for using rename to overwrite a different product? Was under impression that this would be restricted and a warning will block users from renaming to existing products. If allowed, server version history code would be the most impacted for this case. 

Also for the standard warning in above screenshot, aligning the symbol with the text would be a nice fix.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-:-NyQEuub0eVN0oA0yawM:b-b6ucr6)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
Yeah, I think that's a good point. It's probably best that we don't allow overwriting using the rename feature. I've changed the logic to disable the button if the new UUID would overwrite an existing product. I've also shortened the rename warning message.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-:-NyR8w4v4BB7ohzyhsaq:b-bt41th)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

**Review by yileifeng — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288#-:-Nz-k3dD3k3ICTuWpwLR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/288)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
