### PR TITLE
Add timeslider layer array editing

### PR DESCRIPTION
**Pull request by spencerwahl**
For https://github.com/ramp4-pcar4/story-ramp/issues/329

Duplicated the component changes onto here and added a new input to the timeslider editor where you can put a comma separated list of layerIDs

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/208)

### CODE REVIEW

**Review by mohsin-r — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/208)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[`src/components/editor/map-editor.vue` line 222 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/208#-NV0ii2d0xId05-fxMbL:-NV0ii2eDkep1CYyy_aN:bvol3jk) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1d60500deffd5f1f3023c6e63998c14181e5a9cc/src/components/editor/map-editor.vue#L222)):*
> ```Vue
>     onTimeSliderInput(property: 'range' | 'start' | 'attribute' | 'layers', index: number, value: string): void {
>         if (property === 'layers') {
>             console.log(value);
> ```

Rogue console log

**Review by mohsin-r — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/208)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by yileifeng — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/208)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/208)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Pull request merged**
