### PR TITLE
Reduce build size by removing dupe bundled RAMP

### LINKED ISSUE #380: Double-Stuffed Build
## Description

A great thing for an Oreo. A bad thing for a Respect Editor.

From what I can tell, the live editor build is bundling the RAMP library twice. Clues:

- The RAMP "version" message appears twice in the console. Sometimes with different version numbers.
- I can see RAMP code appearing twice in the `main--HASH.js` build file.
- The built javascript file is Twenty Six Bleedin' Megabtyes.

I suspect that the RAMP Config editor is [consuming RAMP](https://github.com/ramp4-pcar4/config-editor/blob/33cc395c5ecef0c8e794c89c2c29befd0d6f2be0/src/main.ts#L9), gets bundled & built, pushed to NPM. RESPECT editor then [consumes it twice](https://github.com/ramp4-pcar4/storylines-editor/blob/824dec826ccac5ced55a9409d5256120dfd9c06f/package.json#L28), once via RAMP library, second time via RAMP Config Editor library.

Obviously want to stop this.

## Environment

DOMM, Disrespectful on Dev

## Possible solution

Some ideas from a non-build-expert.

1. Looking at [this line](https://github.com/ramp4-pcar4/storylines-editor/blob/824dec826ccac5ced55a9409d5256120dfd9c06f/src/components/map-editor.vue#L54), can we just stop importing the RAMP library in RESPECT Editor? From what I can tell, we are only importing [the CSS file](https://github.com/ramp4-pcar4/storylines-editor/blob/824dec826ccac5ced55a9409d5256120dfd9c06f/src/main.ts#L10). Would be reeeeeeeeal nice if solution is that easy, since everything that follows it nasty. Biggest gotcha I see here is you can't refresh RAMP in RESPECT without also releasing a new tag on RAMP Config Editor. Which is what the patch number on the version is suited for, but still seems a tad silly.
1. Change RAMP Config Editor to import RAMP via `package.json` instead of having a local copy of RAMP build. Then cross fingers and hope RESPECT editor build has tree shaking smart enough to drop the duplicate.
1. For the above to work, a strategy will need to be in place to ensure that RAMP Config Editor and RESPECT Editor are always pointing to the same version of RAMP on NPM. This sort of ties in with the gotcha mentioned in the first idea.
1. Make the RAMP Config editor source a subfolder of RESPECT editor. Now they can share the same import. Lazy but effective. Breaks the ability to grab RAMP Config editor as a single unit for other purposes.
1. Start investing in deeply understanding builds and bundlers, which is hurting us everywhere (https://github.com/ramp4-pcar4/ramp4-pcar4/issues/1528).

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
Closes #380 

### Changes
- [FIX] duplicate bundled RAMP in plugin builds
- updated dependencies for config editor `v3.5.2`, storylines `v3.2.2` and RAMP `v4.8.0`

### Testing

Ensure main.js build file is ~17MB + test RAMP instance functionality.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/382)

### CODE REVIEW

**Review by mohsin-r — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
