### PR TITLE
Add required and default metadata fields

### LINKED ISSUE #151: Mark required metadata fields and defaulting
On the metadata page, mark any required fields as non-empty to prevent the user from proceeding to the main slide editor until filled. The `UUID` and `Title` fields would probably fall under this category. In addition for creating new products, it can be helpful to auto-fill fields with default values such as Date Modified with the current date.

### PR DESCRIPTION
**Pull request by yileifeng**
Closes #151 

**Changes**: 
- marks UUID field as required and cannot proceed to editor with empty required fields (also cannot proceed to editor if changed UUID for existing product - not sure if UUID should be modifiable for existing products through this page)
- adds default date modified field to be set to current date when creating a new product
- clears metadata contents when loading in an existing product and failing

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Messed up rebase, fixing

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166#-:-NTFGBd2-zLXADGDI7xj:bgfssyu)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @mohsin-r and @RyanCoulsonCA)

**Review by yileifeng — COMMENTED** [review]
Rebased.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166#-:-NTFOHLw9frloNOs9zLl:bncvegj)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mohsin-r and @RyanCoulsonCA)

**Review by spencerwahl — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Pull request merged**
