### PR TITLE
Implement metadata editor redesign

### PR DESCRIPTION
**Pull request by gordlin**
### Related Item(s)
Issues:
#374 
#399 

### Changes
- Implemented redesign of both metadata editor pages, as well as all related functionality.

### Notes
**NOTE**: The new product details form is **not** implemented in this PR, so the old one is still here. It has a separate issue: #400. Should only be done **after** this PR is merged, or should at least base its branch on this one.

*Old 'Edit Existing' page*:
image

*New 'Edit Existing' page* (before UID & load):
image

*New 'Edit Existing' page* (after UID & load; black box hidden on actual page):
image

*Old 'Create New' page*:
image

*New 'Create New' page* (black box hidden on actual page):
image

### Testing
Steps:
1. Select any language, click onto 'Edit Existing'. Enter any existing product ID, click enter OR press the load button. Notice the very large spinner, and the info-text about loading times. Once loading's done, view the result.
2. If there's history, you'll see some text confirming it and a button to open up the history results table. If not, the text will indicate it, and the button will be hidden. The form should show the correct metadata information.
3. Go back to the New Storylines page. Try creating a new storyline with the form; it should still work.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)

### CODE REVIEW

**Review by yileifeng — CHANGES_REQUESTED** [review]
Nice enhancements :+1:

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-:-O7_Vpib4MPalkHq4uLM:b-7vio6j)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gordlin)

___
*[`src/components/metadata-editor.vue` line 13 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_UnYzEK8M3u5JndGS:-O7_UnYzEK8M3u5JndGT:b-qwuyw4) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L13)):*
> ```Vue
>                     </div>
>                     <div class="flex flex-row md:flex-col gap-3 justify-between text-right">
>                         <router-link
> ```

This should not be needed, the language toggle should be page specific so would only appear when we load the Canada.ca template. If we load the page with Canada.ca template now we would get two instances of the language hyperlink.
___
*[`src/components/metadata-editor.vue` line 38 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_XctI3WL9FaKyjb4X:-O7_XctI3WL9FaKyjb4Y:b-chs281) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L38)):*
> ```Vue
> 
>                     <section>
>                         <label class="font-bold">{{ $t('editor.uuid') }}</label>
> ```

Few points regarding UUID section: 
- mark "(required)" text as red font
- reduce padding between UUID label and input box 
- add a "clear button" to the input as per the mockups
___
*[`src/components/metadata-editor.vue` line 753 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_Yy5l35DAVBJwqeC2:-O7_Yy5l35DAVBJwqeC3:b-fkqw5f) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L753)):*
> ```Vue
>         } catch (err: any) {
>             if (err.name === 'AbortError' || err instanceof PointerEvent) {
>                 Message.success(`Product retrieval manually aborted.`);
> ```

Need a translation here, unofficial Google translate marked with a 0 in the CSV file is fine. Noticed there are a few more instances of non-translations in this component so if you could fix those at the same time would be great. Also, I don't think we should display the green check in the popup message when cancelling a product load from a user perspective.

**Review by yileifeng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gordlin)

___
*[`src/components/metadata-editor.vue` line 13 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_UnYzEK8M3u5JndGS:-O7_b_S03eB1Iib5pNJ5:bv9ngkg) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L13)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

This should not be needed, the language toggle should be page specific so would only appear when we load the Canada.ca template. If we load the page with Canada.ca template now we would get two instances of the language hyperlink.
</blockquote></details>

Ah my bad revisiting the mockups it looks like they have separate view for non-Canada.ca template in which case this section is needed. However, we still need a way to conditionally render the element in case we are using the template to prevent duplicate instances.

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

___
*[`src/components/metadata-editor.vue` line 5 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eTCEQBiLWS6aAz1YC:-O7oDLma2MlciM-Zywru:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L5)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

You can remove the empty `class` attribute here
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 13 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_UnYzEK8M3u5JndGS:-O7oDN5M3vUcoFM8vd4h:ba7olny) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L13)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Ah my bad revisiting the mockups it looks like they have separate view for non-Canada.ca template in which case this section is needed. However, we still need a way to conditionally render the element in case we are using the template to prevent duplicate instances.
</blockquote></details>

Donethanks! The toggle will be hidden on the Canada.ca template and show everywhere else.
___
*[`src/components/metadata-editor.vue` line 38 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_XctI3WL9FaKyjb4X:-O7oDSrI83EO3sutII3E:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L38)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Few points regarding UUID section: 
- mark "(required)" text as red font
- reduce padding between UUID label and input box 
- add a "clear button" to the input as per the mockups
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 173 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eTvwd9ahD9JuceZ_5:-O7oDaBW-GX9ejgBc4V9:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L173)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

You can remove this if it's unused
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 239 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eU0DUDEKUgyDxDk10:-O7oDbDjAo-klbtvQYOs:bicg1xv) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L239)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

I think the condition `editExisting && loadStatus === 'loaded'` would be cleaner here as we want to display this for existing products that have finished loading.
</blockquote></details>

The new condition wouldn't work, since the metadata tables won't display for the `Create New Storylines` page (as editExisting is not true there). Existing condition might have to stay.
___
*[`src/components/metadata-editor.vue` line 325 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7e_txP0YZQDigWkQzj:-O7oDkDRATvzL-nJyuMV:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L325)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This can be removed as well
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 422 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7ea-Mu9zc2Bdoelg0G:-O7oDlyOBX5zAX5ZerYf:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L422)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This is a pre-existing problem as well, but it should have a translation
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 723 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eSLfp0XsDRRlrtOee:-O7oDnMZ8VluZW6SkQ8m:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L723)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Need a translation here too. Looks like this one was already hardcoded previously but we should fix it anyway!
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 753 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7_Yy5l35DAVBJwqeC2:-O7oDpiH7-QpEXTwZ-ZD:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L753)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Need a translation here, unofficial Google translate marked with a 0 in the CSV file is fine. Noticed there are a few more instances of non-translations in this component so if you could fix those at the same time would be great. Also, I don't think we should display the green check in the popup message when cancelling a product load from a user perspective.
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 755 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eSansExz6I8YisIEC:-O7oDpOp-7HgbX2vLZ01:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L755)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Translation needed here
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 766 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eSZBND_M4GSama-UF:-O7oDqcx21CDIU-y-pW3:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L766)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Translation needed here
</blockquote></details>

Donethanks!

**Review by yileifeng — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @gordlin and @RyanCoulsonCA)

___
*[`src/components/metadata-editor.vue` line 24 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7oWr3q6sqxxFq1TJuD:-O7oWr3q6sqxxFq1TJuE:bdjouzl) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/376bbba8b17b36c6e9e0dffb48f1f477ece9f4ea/src/components/metadata-editor.vue#L24)):*
> ```Vue
>                             }"
>                         >
>                             <a class="sub-link">
> ```

A bit nitpicky, but I prefer if these anchor elements were styled as buttons (no underline, darker font color) to look less like a hyperlink and more like app functionality. For reference, something along the lines of the "old" rename functionality: 



Same applies to the other "sub-link" class elements below (swap config lang, click here to change UUID). 
___
*[`src/components/metadata-editor.vue` line 45 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7oZH-r1mgnRFSmn5ia:-O7oZH-r1mgnRFSmn5ib:b-69966e) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/376bbba8b17b36c6e9e0dffb48f1f477ece9f4ea/src/components/metadata-editor.vue#L45)):*
> ```Vue
>                         <label class="font-bold mb-0"
>                             >{{ $t('editor.uuid') }}
>                             <span class="text-red-500 font-normal">{{ $t('editor.uuid.required') }}</span></label
> ```

Very low contrast WAVE error (3.76:1) on the (required) label. 
___
*[`src/components/metadata-editor.vue` line 68 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7oYzcz4j1VBzQUCAKV:-O7oYzd-Ex2q_fnGsiMf:b-t6avzg) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/376bbba8b17b36c6e9e0dffb48f1f477ece9f4ea/src/components/metadata-editor.vue#L68)):*
> ```Vue
>                                 <input
>                                     class="editor-input mt-0 flex-2"
>                                     type="search"
> ```

Empty + missing form label when running WAVE on this search input

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @gordlin and @yileifeng)

___
*[`src/components/metadata-editor.vue` line 239 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eU0DUDEKUgyDxDk10:-O7p52gz2hAHzJHFb5bM:b-7q2axg) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L239)):*
<details><summary><i>Previously, gordlin (Gordon Lin) wrote…</i></summary><blockquote>

The new condition wouldn't work, since the metadata tables won't display for the `Create New Storylines` page (as editExisting is not true there). Existing condition might have to stay.
</blockquote></details>

Ah, I understand. I didn't catch that the rest of the metadata form was in this section as well. In that case maybe just replace the condition with `!editExisting || loadStatus === 'loaded'` since it's logically equivalent to the condition you have already have (but just removes the double negative).

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7pKHNy7E8A32Zu7C4g:-O7pKHNy7E8A32Zu7C4h:b-e2jyc0) (no related file):*
Note: Added translations for all of the popup messages/warnings/infos. I think the metadata page is now fully "translated". Let me know if I missed any.

___
___
*[`src/components/metadata-editor.vue` line 239 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7eU0DUDEKUgyDxDk10:-O7pJe3lAlVNMBUOUaBj:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f3afcb29d58983e67fd943d8c0c5645ad06b9b0f/src/components/metadata-editor.vue#L239)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Ah, I understand. I didn't catch that the rest of the metadata form was in this section as well. In that case maybe just replace the condition with `!editExisting || loadStatus === 'loaded'` since it's logically equivalent to the condition you have already have (but just removes the double negative).
</blockquote></details>

Donethanks!
___
*[`src/components/metadata-editor.vue` line 24 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7oWr3q6sqxxFq1TJuD:-O7pJjaL3OTwoQDAixnh:b-w8lq07) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/376bbba8b17b36c6e9e0dffb48f1f477ece9f4ea/src/components/metadata-editor.vue#L24)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

A bit nitpicky, but I prefer if these anchor elements were styled as buttons (no underline, darker font color) to look less like a hyperlink and more like app functionality. For reference, something along the lines of the "old" rename functionality: 



Same applies to the other "sub-link" class elements below (swap config lang, click here to change UUID).
</blockquote></details>

Changing the link colour/removing the underline would make the "Change UUID" text very hard to distinguish from the heading. Personally I'm in favour of leaving the link style, it makes it very distinctive (and hopefully more accessible as a result).

@RyanCoulsonCA thoughts?


___
*[`src/components/metadata-editor.vue` line 45 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7oZH-r1mgnRFSmn5ia:-O7pIvRP18J7qS3muJpv:bfe1ssb) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/376bbba8b17b36c6e9e0dffb48f1f477ece9f4ea/src/components/metadata-editor.vue#L45)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Very low contrast WAVE error (3.76:1) on the (required) label.
</blockquote></details>

 Donethanks!
___
*[`src/components/metadata-editor.vue` line 68 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O7oYzcz4j1VBzQUCAKV:-O7pIwpj3ei5R-Rykqq2:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/376bbba8b17b36c6e9e0dffb48f1f477ece9f4ea/src/components/metadata-editor.vue#L68)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Empty + missing form label when running WAVE on this search input
</blockquote></details>

Donethanks!

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O8hWRmk2neQQqaQt0vI:-O8hWRmk2neQQqaQt0vJ:b-sinizz) (no related file):*
Latest push fixes a merge conflict. There should be no differences.

___

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O8hWRmk2neQQqaQt0vI:-O8hrASE8Kje1Wyyh5-1:bpysyob) (no related file):*
<details><summary><i>Previously, gordlin (Gordon Lin) wrote…</i></summary><blockquote>

Latest push fixes a merge conflict. There should be no differences.
</blockquote></details>

Also reduced spacing between the label and inputs by a little bit.

___

**Review by szczz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: all files reviewed, 5 unresolved discussions (waiting on @gordlin and @RyanCoulsonCA)

___
*[`src/components/metadata-editor.vue` line 48 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O9LI0dNBxYJm7BTXjP7:-O9LI0dNBxYJm7BTXjP8:b-8dxzk8) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1321184be06a03ff97d75f4efc7e3b4ab7fa577d/src/components/metadata-editor.vue#L48)):*
> ```Vue
>                         >
>                         
>                         <span v-if="editExisting && loadStatus == 'loaded'" class="p-1">
> ```

===
___
*[`src/components/metadata-editor.vue` line 54 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O9LI93Z1RO-DWxK5AkS:-O9LI93Z1RO-DWxK5AkT:b2nh75k) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1321184be06a03ff97d75f4efc7e3b4ab7fa577d/src/components/metadata-editor.vue#L54)):*
> ```Vue
>                                     renaming = !renaming;
>                                     changeUuid = '';
>                                     warning = warning == 'rename' ? 'none' : warning;
> ```

===

**Review by gordlin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @RyanCoulsonCA and @szczz)

___
*[`src/components/metadata-editor.vue` line 48 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O9LI0dNBxYJm7BTXjP7:-O9Ltvt_8_Iy-9GbrtOa:b-peca60) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1321184be06a03ff97d75f4efc7e3b4ab7fa577d/src/components/metadata-editor.vue#L48)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

===
</blockquote></details>

Don't know how this happened so many times. Donethanks!
___
*[`src/components/metadata-editor.vue` line 54 at r7](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-O9LI93Z1RO-DWxK5AkS:-O9Lu16FE81mY9Y6u1SV:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1321184be06a03ff97d75f4efc7e3b4ab7fa577d/src/components/metadata-editor.vue#L54)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

===
</blockquote></details>

Donethanks!

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: all files reviewed, 5 unresolved discussions (waiting on @szczz and @yileifeng)

**Review by IshavSohal — APPROVED** [review]
Looks great!

> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403#-:-OAJoSiO6O0jWLftwIE9:b9bkkp1)* status: all files reviewed, 5 unresolved discussions (waiting on @gordlin, @RyanCoulsonCA, @szczz, and @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: all files reviewed, 3 unresolved discussions (waiting on @gordlin, @IshavSohal, @RyanCoulsonCA, and @yileifeng)

**Review by RyanCoulsonCA — APPROVED** [review]

**Review by spencerwahl — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r5, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: all files reviewed, 3 unresolved discussions (waiting on @gordlin, @RyanCoulsonCA, and @yileifeng)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: all files reviewed, 3 unresolved discussions (waiting on @gordlin, @IshavSohal, @RyanCoulsonCA, @spencerwahl, and @szczz)

**Review by RyanCoulsonCA — APPROVED** [review]

**Review by IshavSohal — APPROVED** [review]

**Review by yileifeng — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/403)* status: all files reviewed, 3 unresolved discussions (waiting on @gordlin, @RyanCoulsonCA, @spencerwahl, and @szczz)

**Pull request merged**
