### PR TITLE
replace RAMP build files with npm

### LINKED ISSUE #326: RAMP v4.5.0
Found by James in 2024-06-18 Testing Party

## Description

v4.6.0 has a number of fixes. Also it looks like the Storylines repo is on an even older version of RAMP (from last October). Bit late to raise this I guess; kinda thing you'd want in before the big testing.

From Dan:
I'm a bit confused why this is the case; do our build processes not grab the latest version of RAMP and Storylines? Have we not integrated the npm packages for RAMP and Storylines? Or if we have, are the npm packages not being updated consistently?

### PR DESCRIPTION
**Pull request by yileifeng**
### Related Item(s)
Closes #326, #354

### Changes
- Removed RAMP build files and integrated RAMP through NPM package

### Notes
- Map instances in preview do not work, likely requires https://github.com/ramp4-pcar4/story-ramp/pull/450 to be merged first to be fixed

### Testing
RAMP config editor outputs maps that can be previewed correctly.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363)

### CODE REVIEW

**Review by RyanCoulsonCA — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`src/components/map-editor.vue` line 54 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363#-O2AxM7iE9woJ4btG4AU:-O2AxM7iE9woJ4btG4AV:bbtwynl) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1b7260edd9f2b802b41866987d272fe0424ea8bf/src/components/map-editor.vue#L54)):*
> ```Vue
> import defaultConfig from '../../ramp-default.json';
> import TimeSliderEditorV from './helpers/time-slider-editor.vue';
> import { createInstance } from 'ramp-config-editor_editeur-config-pcar';
> ```

I believe this function is different than the one in the `ramp-pcar` package and it instead instantiates the editor. Currently if you go to the map editor panel, it's just displaying a map instead of the map editor.

**Review by yileifeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/map-editor.vue` line 54 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363#-O2AxM7iE9woJ4btG4AU:-O2BDKAI23nr0QAj2v9p:bhast6g) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/1b7260edd9f2b802b41866987d272fe0424ea8bf/src/components/map-editor.vue#L54)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

I believe this function is different than the one in the `ramp-pcar` package and it instead instantiates the editor. Currently if you go to the map editor panel, it's just displaying a map instead of the map editor.
</blockquote></details>

Good catch reverted this

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by szczz — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by dnlnashed — APPROVED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)

**Review by yileifeng — COMMENTED** [review]
Also included the updated NPM Storylines plugin changes in this PR (see https://github.com/ramp4-pcar4/story-ramp/pull/455). Preview mode should be functional for all panel types, and maps should load without issues. Any additional testing on this would be helpful.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/363#-:-O46yCPRDvGxImEwb93i:br3c1tt)* status: 6 of 10 files reviewed, all discussions resolved (waiting on @dnlnashed, @RyanCoulsonCA, and @szczz)

**Pull request merged**
