### PR TITLE
Scroll to dynamic content on change

### PR DESCRIPTION
**Pull request by spencerwahl**
Porting over changes for https://github.com/ramp4-pcar4/story-ramp/issues/349

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/224)

### CODE REVIEW

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by roryhofland — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/224)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Pull request merged**
