### PR TITLE
Fix fullscreen using wrong map

### PR DESCRIPTION
**Pull request by spencerwahl**
porting over changes for ramp4-pcar4/story-ramp#335

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/223)

### CODE REVIEW

**Review by mohsin-r — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/223)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/223)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

**Review by yileifeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)

**Pull request merged**
