### PR TITLE
Error handling

### LINKED ISSUE #294: Editor Button/Input UI Issues
## Description

CSS changes were lost for the video slide editor from one of the more recently merged PRs. 

image

Another case for the slideshow editor: 

image

## Steps to reproduce

Navigate to video panel in slide editor.

### PR DESCRIPTION
**Pull request by roryhofland**
Closes [#294](https://github.com/ramp4-pcar4/story-ramp/issues/294) and #156.

### Changes (updated)
- added checks and UI indications when various errors occur
    - loading a malformed product (missing lang config, malformed config file)
    - creating product without a UUID
    - creating product with existing UUID
    - attempting to load product without server connection
- metadata fields are now cleared when loading a nonexistant/malformed config
- centered loading spinner icon

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/154)

### CODE REVIEW

**Review by mohsin-r — CHANGES_REQUESTED** [review]
Looks pretty good for the most part. Just one issue I found when testing:

For the duplicate UUID check, it only updates when the input field loses focus. So I could type in a duplicate and then directly press "Next" without clicking anywhere else, and I would receive no warning. 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/154#-:-NS82Fn88Gdss1iJqpSr:by1iljq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by roryhofland — COMMENTED** [review]
Donethanks. Now the check happens on input, and there is an extra confirmation modal before proceeding to the slide editor.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/154#-:-NSv7kyaDHiQhNRfP9N_:bpjcf06)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mohsin-r)

**Review by RyanCoulsonCA — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by mohsin-r — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Review by yileifeng — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)

**Pull request merged**
