### PR TITLE
add subscript and superscript button to text editor

### LINKED ISSUE #160: Add subscript and superscript options to the Markdown editor
I'm not clear on how much flexibility we have with the Markdown editor, but it would be grand if there were buttons to surround numbers in `<sub>` or `<sup>` tags for subscript and superscript characters

Subscript: H<sub>2</sub>O
Superscript: 3<sup>2</sup>

### PR DESCRIPTION
**Pull request by RyanCoulsonCA**
Closes #160 

This PR adds a menu that allows you to add subscripts and superscripts.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/168)

### CODE REVIEW

**Review by mohsin-r — APPROVED** [review]
Not a big deal whatsoever, but I was curious if we could get the `x^2^` syntax that some editors allow. And the same thing for subscripts. https://www.markdownguide.org/extended-syntax/#subscript

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/168#-:-NSCnlcB3muEXoF1oiMT:b-j5b147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by roryhofland — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by RyanCoulsonCA — COMMENTED** [review]
> Not a big deal whatsoever, but I was curious if we could get the x^2^ syntax that some editors allow. And the same thing for subscripts. https://www.markdownguide.org/extended-syntax/#subscript

I looked into this and it doesn't seem like there's any easy way for us to support this. It doesn't support it natively, and none of the extensions built-in to the app support it either, so we'd probably need to modify the source code. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/168#-:-NSHjay08RtUGg7R2Y3r:bdgnti7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by mohsin-r — APPROVED** [review]
Makes sense, its probably not worth the effort then lol. All good.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/168#-:-NSI1wtU0Qk1969jVpWF:b-jdknc9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Review by yileifeng — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/168)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)

**Pull request merged**
